// Programme journey narratives — sourced from the School of Leadership, Human Protection and
// Climate Justice Programme Journey documents. Rendered on the programme pages above the register.

const T = 'assets/thumb/';

export const JOURNEY = {

  sol: {
    eyebrow: 'Programme journey',
    title: 'One community. One leadership journey. Many pathways to lead.',
    body: 'Communities do not stand still. Children become adolescents, adolescents become young adults, and each generation inherits new opportunities, responsibilities and challenges. Projects are time-bound by nature; communities continue long after they conclude. Progress therefore depends not only on what projects achieve during implementation, but on what communities are able to carry forward after they end.',
    pull: 'The challenge is not simply how to implement better projects. It is how to ensure that every generation is equipped to participate, organise, lead, and prepare the next.',
    chipsLabel: 'What a leadership ecosystem has to hold',
    chips: [
      'A connected pathway across life stages',
      'Mentorship that is routine, not exceptional',
      'Community institutions as permanent spaces',
      'Local knowledge that transfers between generations',
      'Rights understood alongside capability',
      'Succession that does not depend on a project',
    ],

    cascade: {
      num: '01',
      title: 'Why leadership is lost between generations',
      body: 'Leadership rarely fails at one moment. It leaks away where a pathway ends and nothing follows. Select a stage to see how the loss compounds, and what the School of Leadership puts in its place.',
      colA: 'How it compounds',
      colB: 'What the programme builds',
      steps: [
        { label: 'Participation tied to one project', img: T + 'sdg-partnership.png',
          detail: 'Opportunities to participate are created and withdrawn on a project calendar.',
          a: 'When the project closes, the space to speak closes with it.',
          b: 'Child Parliaments, adolescent groups and youth platforms rooted in the same community institutions across projects.' },
        { label: 'No bridge between age groups', img: T + 'right-participation.png',
          detail: 'A child who leads at twelve finds nothing designed for her at sixteen.',
          a: 'Confidence built in one stage is not carried into the next.',
          b: 'A connected pathway — Child Parliament to PANCHI to youth groups to fellowship to community leadership.' },
        { label: 'Knowledge held by individuals', img: T + 'sdg-quality-education.png',
          detail: 'What a community has learned lives in one or two people’s memory.',
          a: 'When those people move or migrate, the learning goes with them.',
          b: 'Documentation, peer learning networks and community-owned knowledge systems.' },
        { label: 'Facilitation stays external', img: T + 'sdg-reduced-inequalities.png',
          detail: 'Collective action depends on someone from outside convening it.',
          a: 'Local ownership never fully forms, and momentum stalls between visits.',
          b: 'Fellows trained to accompany rather than direct, and Community Resource Persons drawn from the village itself.' },
        { label: 'Institutions without successors', img: T + 'sdg-peace.png',
          detail: 'Committees exist on paper but have no pipeline of people ready to hold them.',
          a: 'Institutions struggle to sustain momentum and quietly go dormant.',
          b: 'Structured leadership succession, institutionalised mentoring and institutions treated as permanent, not project-specific.' },
        { label: 'Capacity rebuilt, not compounded', img: T + 'sdg-gender-equality.png',
          detail: 'Each new challenge starts from a standing start.',
          a: 'Communities repeatedly rebuild capacity instead of continuously strengthening it.',
          b: 'An architecture where every intervention leaves behind stronger leaders and stronger institutions than it found.' },
      ],
    },

    tiers: {
      num: '02',
      title: 'Leadership across life stages',
      body: 'Leadership cannot be developed through a single intervention, nor does it emerge at one stage of life. Each stage serves a distinct purpose — not simply preparing individuals for the next programme, but preparing them for a greater role in shaping the lives of others. Select a stage to read what it is for.',
      note: 'Across every stage the purpose stays constant: an expanding sense of responsibility, from finding one’s own voice, to enabling the voices of others, to building communities capable of continuously creating leaders.',
      rows: [
        { label: 'Childhood · discovering voice', w: '58%', art: 'assets/thumb/right-participation.png',
          note: 'Through Child Parliaments, children experience participation, democratic decision-making and representation for the first time. Leadership is introduced not as authority, but as the confidence to speak, listen and act together.',
          items: ['Child Parliaments', 'Democratic elections', 'Peer learning groups', 'School governance platforms'] },
        { label: 'Adolescence · building identity and agency', w: '69%', art: 'assets/thumb/sdg-gender-equality.png',
          note: 'Through PANCHI, girls question harmful gender norms, strengthen self-confidence and recognise their rights — shifting from recipients of information to facilitators, peer educators and advocates.',
          items: ['PANCHI', 'Safe peer spaces', 'Peer educators', 'SRHR and rights learning'] },
        { label: 'Youth · taking collective responsibility', w: '80%', art: 'assets/thumb/sdg-partnership.png',
          note: 'Leadership extends beyond personal growth to collective action — organising communities, engaging Panchayats and public institutions, and bringing people together to solve problems.',
          items: ['Youth groups', 'Panchayat engagement', 'Campaigns', 'Community mobilisation'] },
        { label: 'Fellowship · enabling others to lead', w: '90%', art: 'assets/thumb/sdg-quality-education.png',
          note: 'Fellows are no longer prepared simply to lead; they are prepared to create leadership in others — accompanying communities rather than directing them.',
          items: ['Community immersion', 'Constitutional values', 'Facilitation practice', 'Institution building'] },
        { label: 'Community leadership · sustaining the journey', w: '100%', art: 'assets/cj/circle-discussion.png',
          note: 'Not an end point but a renewal of the cycle. Experienced leaders become resource persons, mentors and institutional leaders who prepare the next generation to take their place.',
          items: ['Community Resource Persons', 'Local governance', 'Mentorship', 'Entitlement accompaniment'] },
      ],
    },

    toc: {
      num: '03',
      title: 'Theory of change',
      body: 'Communities are able to nurture, sustain and renew leadership across generations, enabling individuals and institutions to collectively realise rights and lead their own development. Six reinforcing pathways carry that goal.',
      fields: ['Community outcome', 'Ecosystem outcome', 'Critical enabler', 'Illustrative indicator'],
      paths: [
        { label: 'Leadership across the life course',
          detail: 'A connected pathway from childhood participation to community leadership.',
          v: ['Individuals demonstrate confidence, agency and collective leadership',
              'Leadership becomes embedded within community institutions',
              'Experiential learning, mentoring, peer learning and community action',
              'Leadership competencies, agency and participation across life stages'] },
        { label: 'Progressive rights and entitlements',
          detail: 'Rights understood, claimed and enabled at every stage of life.',
          v: ['Communities increasingly understand, claim and enable rights',
              'Rights become embedded in community institutions and decision-making',
              'Rights-based learning, institutional convergence and community facilitation',
              'Access to rights, entitlements and public services'] },
        { label: 'An intergenerational pipeline',
          detail: 'Child Parliament → adolescent groups → youth → fellows → community leaders.',
          v: ['Children, adolescents and youth assume leadership roles',
              'A strong intergenerational leadership pipeline',
              'Leadership platforms, mentorship and succession pathways',
              'Leadership progression across community platforms'] },
        { label: 'Collective action and governance',
          detail: 'Community mobilisation, local governance and engagement with public systems.',
          v: ['Communities organise collective action and engage public systems',
              'Strong, accountable and self-sustaining community institutions',
              'Community institutions, partnerships and long-term accompaniment',
              'Institutional functionality and collective action outcomes'] },
        { label: 'Leadership applied across themes',
          detail: 'The same leadership put to work in protection, governance, livelihoods and resilience.',
          v: ['Leadership strengthens protection, governance, livelihoods and resilience',
              'Leadership reinforces all thematic programme journeys',
              'Integrated programme architecture and cross-sector partnerships',
              'Community-led thematic outcomes and institutional strengthening'] },
        { label: 'A self-renewing ecosystem',
          detail: 'Communities mentor future leaders and sustain change independently.',
          v: ['Communities mentor future leaders and sustain change independently',
              'A self-renewing leadership ecosystem',
              'Leadership succession, knowledge systems and digital learning',
              'Leadership continuity, institutional sustainability and community ownership'] },
      ],
    },

    pairs: {
      num: '04',
      title: 'From developing leaders to sustaining leadership systems',
      body: 'Over three decades the School of Leadership has shown that leadership can be nurtured across childhood, adolescence, youth and adulthood. The next challenge is to ensure leadership renews itself without remaining dependent on external facilitation. Success will not be measured by the number of leaders trained, but by a community’s ability to produce, mentor and sustain leaders from within.',
      colA: 'Today',
      colB: 'Next five years',
      colC: '',
      artA: 'assets/story/sm-ink-pair.png',
      artB: 'assets/story/sm-ink-crowd.png',
      capA: 'Leadership is carried by individuals who were reached by a programme. It grows where facilitation reaches.',
      capB: 'Leadership is carried by a community that reproduces it. It grows whether or not anyone is visiting.',
      rows: [
        { a: 'Individual leaders developed through programmes', b: 'Leadership systems that renew themselves within communities' },
        { a: 'Participation as representation in Gram Sabhas and committees', b: 'Participation as shared governance — influencing decisions and working alongside institutions as partners' },
        { a: 'Community knowledge held in memory and individual experience', b: 'Community intelligence — local evidence organised, preserved and used to guide action' },
        { a: 'Mentorship that happens when someone thinks to offer it', b: 'Institutionalised mentoring between experienced and emerging leaders' },
        { a: 'Structures created for specific projects', b: 'Long-term community institutions that outlast every project' },
        { a: 'Success measured within a project lifespan', b: 'Success measured across generations' },
      ],
    },

    horizons: {
      num: '05',
      title: 'A phased investment roadmap',
      body: 'The next phase is not about expanding programmes alone. It is about strengthening the systems that let communities continuously nurture leaders, realise rights, adapt to changing contexts and sustain collective action after individual projects have ended. Five shifts, each able to stand on its own — mapped in direct consultation with the communities we work with, over a planning process that ran from 2021 to 2026.',
      metaLabel: 'Indicative funding size',
      objLabel: 'Why this matters',
      itemsLabel: 'Strategic priorities',
      ctaLabel: 'Ask for the Full Funding Plan',
      ctaNote: 'Each phase’s full funding plan — budget, results framework and implementation timeline — is ready on request, for this phase alone or as part of a longer commitment to the leadership ecosystem.',
      rows: [
        { label: 'Leaders → leadership systems · 0–12 months', meta: '₹20 lakh – ₹75 lakh',
          obj: 'Child Parliaments, adolescent groups, youth platforms, Community Resource Persons and community institutions increasingly function as interconnected spaces where leadership is transferred and each generation actively prepares the next.',
          items: ['Structured leadership succession pathways across every life stage', 'Institutionalised mentoring between experienced and emerging leaders', 'Community institutions as permanent spaces for leadership development', 'Mechanisms for documenting and transferring local knowledge across generations'] },
        { label: 'Participation → decision-making · 1–2 years', meta: '₹75 lakh – ₹2 crore',
          obj: 'Leadership must enable communities not only to participate in Gram Sabhas and village institutions, but to influence decisions, mobilise resources and work alongside administration as partners in delivery — a shift from representation towards shared governance.',
          items: ['Community-led planning and local decision-making processes', 'Meaningful participation in Gram Sabhas and village institutions', 'Leadership capacities for negotiation, facilitation and public engagement', 'Community–government partnerships based on trust and collaboration'] },
        { label: 'Knowledge → community intelligence · 2–3 years', meta: '₹1 – 4 crore',
          obj: 'Communities already possess deep knowledge of their own realities. The opportunity is to help them organise, preserve and use it. Technology is not a substitute for leadership but an enabler of learning and collaboration.',
          items: ['Community-owned knowledge and learning systems', 'Digital and data literacy among youth and community leaders', 'Technology-enabled platforms for continuous learning and peer exchange', 'Local evidence used for planning, monitoring and advocacy'] },
        { label: 'Individuals → learning communities · 3–5 years', meta: '₹2 – 6 crore',
          obj: 'Leadership becomes sustainable when reflection, peer learning, mentorship and collective problem-solving become ordinary. Every experienced leader becomes a mentor; every institution becomes a learning space.',
          items: ['Peer learning networks across villages and programme areas', 'Intergenerational mentoring platforms connecting youth and community leaders', 'Communities of practice around leadership, rights and governance', 'Documenting and sharing locally developed innovations'] },
        { label: 'Projects → generational change · 5–10 years', meta: '₹6 crore+',
          obj: 'Development is often measured within the lifespan of projects. The School of Leadership measures success across generations, with each project a stepping stone in a much longer journey of community transformation.',
          items: ['Leadership pathways embedded across all programme journeys', 'Long-term community institutions rather than project-specific structures', 'An expanded evidence base for community-led leadership models', 'Partnerships that invest in long-term systems rather than short-term interventions'] },
      ],
    },

    close: {
      num: '06', // horizons restored as '05' (qualitative content only — see horizons.body/rows below)
      title: 'What makes the approach different',
      body: 'Conventional leadership programmes develop a limited number of individuals. DEHAT’s experience suggests leadership only holds when it is designed to be handed on — when each stage prepares people not for the next programme, but for a greater role in shaping the lives of others.',
      chainLabel: 'Where most leadership programmes stop',
      chainStop: 2,
      art: 'assets/story/right-participation.png',
      arrows: [
        { from: 'Training', to: 'Individual confidence' },
        { from: 'Confidence', to: 'Agency and informed decisions' },
        { from: 'Agency', to: 'Collective action and institutions' },
        { from: 'Institutions', to: 'Mentorship of the next generation' },
        { from: 'Succession', to: 'A community that renews its own leadership' },
      ],
    },
  },

  hp: {
    eyebrow: 'Programme journey',
    title: 'Protection begins long before a crisis.',
    body: 'Children rarely enter crisis suddenly. In border regions under strain, risk accumulates gradually across fragmented systems of education, migration, labour, health, protection and justice long before formal intervention occurs. The challenge is not only the absence of protection systems. The deeper challenge is the absence of continuity between them.',
    pull: 'Vulnerability is rarely a single event. It accumulates across disconnected systems where children fall through invisible gaps long before formal protection mechanisms intervene.',
    chipsLabel: 'What the ecosystem is built to do',
    chips: [
      'Identify vulnerability earlier',
      'Sustain continuity longer',
      'Reduce repeated vulnerability',
      'Strengthen community ownership',
      'Preserve continuity across fragmented systems',
      'Sustain protection beyond moments of crisis',
    ],

    cascade: {
      num: '01',
      title: 'How a child falls through',
      body: 'Across high-risk border ecosystems, vulnerability progresses through recognisable stages. System response is often mismatched to that progression. Select a stage to see the mismatch, and what DEHAT does at that point.',
      colA: 'Typical system response',
      colB: 'Where DEHAT works',
      steps: [
        { label: 'School discontinuation begins', img: T + 'issue-school-dropout.png',
          detail: 'Absenteeism, withdrawal from education, or quiet exit from school.',
          a: 'Often treated as temporary dropout with limited follow-up.',
          b: 'Child Parliaments, Village Level Child Protection and Welfare Committees, adolescent platforms and parent networks flag absence early and re-engage the household.' },
        { label: 'Economic distress increases', img: T + 'issue-bread-earner.png',
          detail: 'Pressure builds for migration, work, or early marriage.',
          a: 'Risks remain weakly tracked across community and institutional systems.',
          b: 'Migration tracking systems and repeated family accompaniment record who is moving, where, and with whom.' },
        { label: 'Movement through labour corridors', img: T + 'issue-child-labour.png',
          detail: 'Children move through labour-linked migration pathways, informal transit routes, or unsafe social relationships.',
          a: 'Fragmented visibility across migration, labour and protection systems.',
          b: 'Community vigilance, village-level escalation and Sashastra Seema Bal and border coordination hold visibility across transit and destination.' },
        { label: 'Exploitation intensifies', img: T + 'issue-trafficking.png',
          detail: 'Child labour, unsafe domestic work, elopement-linked exploitation, trafficking risk, or sexual abuse.',
          a: 'Delayed identification and escalation after harm has already intensified.',
          b: 'Trafficking interception, missing-child follow-up and rescue coordination with Child Welfare Committees, Anti-Human Trafficking Units, police, Panchayats and Labour Departments.' },
        { label: 'Disconnection from Systems', img: 'assets/story/sm-school-steps-gate.png',
          detail: 'Children become disconnected from schools, peer systems, community structures and institutional follow-up.',
          a: 'Weak reintegration continuity and inconsistent long-term follow-up.',
          b: 'Psychosocial accompaniment, school re-enrolment, family reintegration, compensation and entitlement linkage, community restoration.' },
        { label: 'Crisis becomes visible', img: T + 'sdg-peace.png',
          detail: 'Rescue, police intervention, or severe harm finally brings the case into institutional view.',
          a: 'Protection systems activate after prolonged vulnerability accumulation.',
          b: 'Referral continuity and long-term follow-up systems designed to reduce repeated vulnerability after the crisis has passed.' },
      ],
    },

    tiers: {
      num: '02',
      title: 'Community-led protection infrastructure',
      body: 'Communities are often the first to recognise vulnerability. DEHAT works to turn local systems into active protection infrastructure connected to institutional response, across four interconnected layers.',
      note: 'Communities are not positioned as passive beneficiaries. They function as active protection actors connected to broader institutional and cross-border protection systems.',
      rows: [
        { label: 'Behaviour change', w: '58%', art: 'assets/art/behaviour-change.png',
          note: 'Shifting norms within families and peer groups so risk is recognised and named locally.',
          items: ['Parent engagement', 'Adolescent engagement', 'Community capacity building', 'Youth leadership', 'Norm shifting'] },
        { label: 'Demand generation', w: '72%', art: 'assets/art/demand-generation.png',
          note: 'Local structures that detect early warning signals and escalate them.',
          items: ['Child Parliaments', 'Village Level Child Protection and Welfare Committees', 'Migration tracking', 'Community vigilance', 'Local escalation systems'] },
        { label: 'System strengthening', w: '86%', art: 'assets/art/system-strengthening.png',
          note: 'Institutional convergence so escalation meets a coordinated response.',
          items: ['Child Welfare Committees & Anti-Human Trafficking Units', 'Police systems', 'Sashastra Seema Bal coordination', 'School systems', 'Panchayats & Labour Departments'] },
        { label: 'Service delivery', w: '100%', art: 'assets/art/service-delivery.png',
          note: 'Response and restoration that continues past the moment of rescue.',
          items: ['Rescue coordination', 'Rehabilitation support', 'Restoration pathways', 'Referral continuity', 'Long-term follow-up'] },
      ],
    },

    toc: {
      num: '03',
      title: 'Theory of change',
      body: 'Children and adolescents are protected from harm, with stronger continuity, community ownership and sustained support systems across border ecosystems under strain. Five pathways carry that goal.',
      fields: ['Human and family outcome', 'Ecosystem outcome', 'Critical enabler', 'Illustrative indicator'],
      paths: [
        { label: 'Early identification',
          detail: 'Child Parliaments, Village Level Child Protection and Welfare Committees, youth groups, migration tracking and community vigilance systems.',
          v: ['Sustained safety, education continuity and protective support within families and communities',
              'More coordinated, visible and continuity-centered protection ecosystems',
              'Standardised onboarding, refresher training, role clarity and scenario-based learning systems',
              '% of adolescents continuing education after intervention or support'] },
        { label: 'Repeated follow-up',
          detail: 'Follow-up cycles, family counselling, peer reinforcement and trigger-based revisits.',
          v: ['Reduced exposure to unsafe migration, child labour, trafficking, child marriage, abuse and repeated vulnerability',
              'Consistent case handling and follow-up across Community Resource Persons, fellows and institutional actors',
              'Clear escalation pathways, communication systems and field guidance protocols',
              '% of child marriage and high-risk adolescent cases supported through community escalation systems'] },
        { label: 'Restoration and reintegration',
          detail: 'Pathways linked to communities, schools, governance systems and institutional follow-up.',
          v: ['Increased family, peer and community support around children and adolescents at risk',
              'Reliable restoration, reintegration and follow-up continuity across the protection journey',
              'Tracking systems, escalation timelines, minimum standards and continuity monitoring',
              '% of rescued or reintegrated children receiving sustained follow-up and reintegration support'] },
        { label: 'Structured case flow',
          detail: 'Identify → Engage → Act → Escalate → Follow-up.',
          v: ['Increased adolescent agency, emotional safety, peer support and access to safer support systems',
              'Stronger community-led protection systems and local escalation pathways',
              'Community vigilance systems, institutional convergence pathways and longitudinal tracking',
              '% of adolescents at risk connected to peer and community support systems'] },
        { label: 'Adolescent engagement',
          detail: 'Platforms, psychosocial accompaniment, peer systems and community-based support structures.',
          v: ['Improved confidence and help-seeking behaviour among adolescents, especially girls',
              'Improved ecosystem visibility, coordination and continuity across long protection journeys',
              'Continuous learning loops, ecosystem coordination systems and outcome visibility',
              '% of adolescent girls reporting increased confidence in seeking support or services'] },
      ],
    },

    pairs: {
      num: '04',
      title: 'From relationship-held continuity to system-held continuity',
      body: 'The model was refined through operational reflection on where continuity weakens in real-world protection ecosystems. Rather than treating these as isolated implementation challenges, they are built into system design.',
      colA: 'Where the ecosystem strains',
      colB: 'How continuity is reinforced',
      colC: 'What this enables',
      artA: 'assets/art/prog-hp.png',
      artB: 'assets/art/system-strengthening.png',
      capA: 'Continuity held by the person who happened to take the case. It ends when they move on.',
      capB: 'Continuity held by the system. The case is followed whoever is on duty.',
      rows: [
        { a: 'Long protection journeys become difficult to track consistently',
          b: 'Maintaining visibility across follow-up cycles, referrals, restoration pathways and long-term accompaniment',
          c: 'Protection systems that can follow through across long and fragmented case journeys' },
        { a: 'Critical knowledge remains dependent on individual actors',
          b: 'Preserving institutional memory, case history, escalation pathways and prior actions across systems',
          c: 'Ecosystems that remember beyond individual staff or frontline workers' },
        { a: 'Vulnerability signals remain fragmented across communities and institutions',
          b: 'Building longitudinal visibility across migration, dropout, trafficking and repeated protection risks',
          c: 'Earlier identification of repeated and emerging vulnerabilities' },
        { a: 'Institutional coordination weakens across actors and jurisdictions',
          b: 'Strengthening escalation visibility, referral continuity and coordinated response pathways',
          c: 'More responsive and coordinated protection response systems' },
        { a: 'Frontline consistency becomes harder to sustain across expanding ecosystems',
          b: 'Supporting continuous learning, operational guidance and reinforcement systems',
          c: 'More reliable and scalable frontline protection ecosystems' },
        { a: 'Restoration continuity weakens after immediate intervention',
          b: 'Strengthening reintegration tracking, accountability and long-term follow-up visibility',
          c: 'Long-term continuity beyond immediate rescue and crisis response' },
      ],
    },

    horizons: {
      num: '05',
      title: 'A phased investment roadmap',
      body: 'The next phase is not about proving that the ecosystem works. It is about ensuring the operational maturity already built can translate into continuity infrastructure and long-horizon partnerships. Not every investment serves the same purpose. Mapped in direct consultation with the communities we work with, over a planning process that ran from 2021 to 2026.',
      metaLabel: 'Indicative funding size',
      objLabel: 'Why this matters',
      itemsLabel: 'Priority investments',
      ctaLabel: 'Ask for the Full Funding Plan',
      ctaNote: 'Each phase’s full funding plan — budget, results framework and implementation timeline — is ready on request, for this phase alone or as a multi-year commitment across all five.',
      rows: [
        { label: 'Restoration continuity · 0–12 months', meta: '₹25 lakh – ₹1 crore+',
          obj: 'Rescue is the visible moment; restoration is where protection is won or lost. This work keeps a case open long after the headline, through reintegration, schooling and compensation.',
          items: ['Reintegration tracking and long-term follow-up', 'Psychosocial accompaniment', 'School re-enrolment after rescue', 'Compensation and entitlement linkage', 'Family and community restoration'] },
        { label: 'Community prevention · 0–12 months', meta: '₹15 lakh – ₹75 lakh',
          obj: 'The cheapest protection case is the one that never opens. Village committees, migration registers and adolescent groups catch risk months before a crisis.',
          items: ['Village Level Child Protection Committees', 'Migration registers and departure tracking', 'Adolescent and parent engagement', 'Community vigilance and local escalation', 'Norm-shifting on early marriage and child labour'] },
        { label: 'Continuity infrastructure · 1–3 years', meta: '₹40 lakh – ₹2 crore+',
          obj: 'Protection journeys run for years across police, Child Welfare Committees, courts and schools. Without shared memory the case restarts at every handover.',
          items: ['Case continuity and institutional memory systems', 'Longitudinal vulnerability visibility', 'Referral and escalation tracking', 'Ecosystem intelligence and outcome dashboards', 'Frontline operational guidance'] },
        { label: 'Institutional convergence · 1–3 years', meta: '₹20 lakh – ₹1 crore',
          obj: 'A border is a jurisdictional seam, and traffickers work the seam. Convergence turns separate mandates into one coordinated response.',
          items: ['Child Welfare Committee, Anti-Human Trafficking Unit and police coordination', 'Sashastra Seema Bal and cross-border protocols', 'District and block convergence forums', 'School and Labour Department linkage', 'Joint review and coordination mechanisms'] },
        { label: 'Replication and capability · 3–5 years', meta: '₹30 lakh – ₹1.5 crore',
          obj: 'What has been built in three districts should be transferable to thirty. That requires curriculum, documentation and training capacity, not just goodwill.',
          items: ['Model documentation and transfer packs', 'Frontline training and certification', 'Partner organisation accompaniment', 'Evidence and evaluation capacity', 'Policy engagement from field practice'] },
      ],
    },

    close: {
      num: '06', // horizons restored as '05' (qualitative content only — see horizons.body/rows below)
      title: 'What makes the approach different',
      body: 'Protection failures rarely emerge from the absence of intervention alone. They emerge when continuity weakens across families, migration journeys, institutions, restoration pathways and long-term follow-up systems. Most protection work is measured at the moment of rescue. DEHAT measures it two years later.',
      chainLabel: 'Where most protection work stops',
      chainStop: 2,
      art: 'assets/art/prog-hp.png',
      arrows: [
        { from: 'Interception', to: 'A child removed from immediate harm' },
        { from: 'Rescue', to: 'A case registered and a system activated' },
        { from: 'Restoration', to: 'Schooling, entitlements and family reintegration' },
        { from: 'Continuity', to: 'Follow-up that outlasts the staff member who opened the file' },
        { from: 'Prevention', to: 'A village that notices the next risk before it becomes a case' },
      ],
    },
  },

  cj: {
    eyebrow: 'Programme journey',
    title: 'Resilience cannot be delivered. It must be built with communities.',
    body: 'Climate variability is no longer a future concern. Changing rainfall patterns, water stress and declining productivity of natural resources already shape how households farm, earn, eat and plan. But climate impacts are rarely experienced as a single environmental event. They travel through livelihoods, food systems, migration patterns, local economies and access to public services.',
    pull: 'What remains within communities after the project ends?',
    chipsLabel: 'Six foundations of a resilient community',
    chips: [
      'Strong local institutions',
      'Capable community leaders',
      'Shared practical knowledge',
      'Trusted peer networks',
      'Linkages to external systems',
      'Organisational capacity and confidence',
    ],

    cascade: {
      num: '01',
      title: 'How vulnerability deepens',
      body: 'Environmental stress triggers a chain of interconnected pressures across livelihoods, migration, nutrition and community systems. This is not a fixed sequence; communities enter it through different pathways. Select a stage to follow the chain.',
      colA: 'How it compounds',
      colB: 'What the programme strengthens',
      steps: [
        { label: 'Rainfall shifts and water stress', img: T + 'sdg-clean-water.png',
          detail: 'Changing rainfall patterns, water stress and increasing environmental uncertainty.',
          a: 'A delayed monsoon reduces agricultural productivity.',
          b: 'LEISA, natural farming practices, seed systems, and soil and water conservation.' },
        { label: 'Yields and soil health decline', img: T + 'sdg-no-hunger.png',
          detail: 'Declining soil health, increasing cultivation risks, dependence on fragile livelihood systems.',
          a: 'Reduced productivity affects household incomes.',
          b: 'Crop diversification, demonstration plots, farmer training, peer learning and exposure visits.' },
        { label: 'Household income falls', img: T + 'sdg-no-poverty.png',
          detail: 'Productive assets become harder to maintain and livelihood choices narrow.',
          a: 'Livelihood insecurity increases dependence on migration or informal labour.',
          b: 'Livelihood diversification and Farmer Resource Centres that reduce dependence on costly external inputs.' },
        { label: 'Migration and informal labour', img: T + 'issue-bread-earner.png',
          detail: 'Seasonal movement in search of work, often away from the household for months.',
          a: 'Migration affects community continuity and local leadership.',
          b: 'Stronger local livelihoods that reduce distress-driven migration and improve household stability.' },
        { label: 'Food and nutrition insecurity', img: T + 'issue-malnutrition.png',
          detail: 'Households prioritise immediate survival over long-term adaptation.',
          a: 'Food insecurity shapes health and wellbeing.',
          b: 'Nutrition-sensitive agriculture, kitchen gardens, pulse cultivation and diversified local food production.' },
        { label: 'Community institutions weaken', img: T + 'sdg-partnership.png',
          detail: 'Limited access to rights and resources weakens the ability of households to recover from shocks.',
          a: 'Institutions become focused on responding to recurring challenges rather than shaping future opportunities.',
          b: 'Aajeevika Adhikar Sangathans and federations that sustain leadership, representation and collective problem-solving.' },
      ],
    },

    tiers: {
      num: '02',
      title: 'The programme in practice',
      body: 'Three interconnected domains reinforce one another through community institutions, local leadership and collective action. The roots are the long-term investments made within communities. The trunk is the collective systems that connect them. The canopy is what emerges as those foundations strengthen.',
      note: 'At the heart of this approach are Aajeevika Adhikar Sangathans and other community institutions that serve as platforms for learning, leadership, representation and local action.',
      rows: [
        { label: 'Canopy · community outcomes', w: '100%', art: 'assets/cj/village-globe.png',
          note: 'What becomes visible as the foundations strengthen over time.',
          items: ['Resilient livelihoods', 'Food and nutrition security', "Women's leadership", 'Access to rights and entitlements', 'Opportunities for young people'] },
        { label: 'Trunk · collective systems', w: '62%', art: 'assets/cj/women-collective.png',
          note: 'The platforms that connect household gains into community capability.',
          items: ['Aajeevika Adhikar Sangathans', 'Federations', 'Krishi Mitras', 'Community resource persons', 'Collective learning spaces'] },
        { label: 'Roots · long-term investments', w: '94%', art: 'assets/cj/plot-field.png',
          note: 'The ecological foundations upon which rural livelihoods depend.',
          items: ['LEISA and natural farming', 'Biodiversity and seed systems', 'Soil and water conservation', 'Crop diversification', 'Natural Resource Management'] },
      ],
    },

    toc: {
      num: '03',
      title: 'Theory of change',
      body: 'Communities are able to adapt to climate stress, reduce vulnerability, strengthen local systems and shape resilient futures across generations. Six pathways carry that goal.',
      fields: ['Community outcome', 'Ecosystem outcome', 'Critical enabler', 'Illustrative indicator'],
      paths: [
        { label: 'Climate-adaptive agriculture',
          detail: 'A staged farming journey — Low External Input Sustainable Agriculture, moving to Natural Farming, and aiming towards Organic Farming certification — alongside diversified crops and natural resource stewardship.',
          v: ['Improved livelihood stability and reduced economic fragility',
              'More diversified and climate-adaptive local production systems',
              'Community mobilisers, Krishi Mitras, demonstration plots and farmer learning systems',
              '% increase in household agricultural income'] },
        { label: 'Food and nutrition',
          detail: 'Kitchen gardens, diversified production, pulse cultivation and nutrition capacity building.',
          v: ['Improved food and nutrition security',
              'Greater household food diversity and nutritional resilience',
              'Community learning systems, women leaders and household engagement',
              '% increase in dietary diversity and pulse consumption'] },
        { label: 'Collective agency',
          detail: 'AASs, federations, collective learning and women-led leadership platforms.',
          v: ['Increased community leadership and collective agency',
              'Stronger community institutions capable of sustaining action',
              'Leadership development, exposure visits and peer learning systems',
              'Participation and leadership indicators across community structures'] },
        { label: 'Rights and governance',
          detail: 'Entitlement support, convergence, Gram Sabha participation and collective representation.',
          v: ['Improved access to rights, entitlements and public systems',
              'Stronger community–government interface and service access',
              'Tracking systems, community facilitators and institutional partnerships',
              'Number and quality of entitlement and service access outcomes'] },
        { label: 'Reduced migration pressure',
          detail: 'Livelihood strengthening, local opportunities and community support systems.',
          v: ['Reduced vulnerability and migration pressure',
              'Stronger continuity within households and communities',
              'Long-term accompaniment, federated structures and local leadership',
              'Migration-related and vulnerability indicators'] },
        { label: 'Youth and future pathways',
          detail: 'PANCHI, youth engagement and local leadership pathways.',
          v: ['Improved youth participation and future opportunity pathways',
              'Intergenerational continuity of resilience systems',
              'Youth platforms, mentorship and community institutions',
              'Youth engagement and leadership indicators'] },
      ],
    },

    pairs: {
      num: '04',
      title: 'From monitoring communities to community intelligence',
      body: 'Resilience does not evolve every three years. Rainfall shifts, water availability fluctuates, migration decisions change from season to season, new women leaders emerge. The next frontier is not measuring resilience more frequently, but enabling communities to continuously understand and respond to the changes shaping their own futures.',
      colA: 'Today',
      colB: 'Future vision',
      colC: '',
      artA: 'assets/cj/registers-desk.png',
      artB: 'assets/cj/community-planning-board.png',
      capA: 'Knowledge sits in registers, reports and one person’s memory. It is read once, at review time.',
      capB: 'Knowledge lives in the community and compounds. It is read continuously, by the people it describes.',
      rows: [
        { a: 'Periodic baseline and endline assessments', b: 'Continuously evolving community intelligence' },
        { a: 'Knowledge stored across registers, reports and individual experience', b: 'Living community knowledge that grows over time' },
        { a: 'Fragmented programme information', b: 'Connected understanding of ecological, social and institutional change' },
        { a: 'Decisions based primarily on periodic reviews', b: 'Adaptive planning informed by real-time community insights' },
        { a: 'Programme reporting for external stakeholders', b: 'Decision-support for communities, grassroots teams and local institutions' },
        { a: 'Organisational learning dispersed across projects', b: 'Institutional memory that strengthens every future programme' },
      ],
    },

    horizons: {
      num: '05',
      title: 'A phased investment roadmap',
      body: 'Not every investment serves the same purpose. Some expand interventions that have already demonstrated impact. Others test new approaches, generate evidence, or build the systems required for communities to continuously adapt. Mapped in direct consultation with the communities we work with, over a planning process that ran from 2021 to 2026.',
      metaLabel: 'Indicative funding size',
      objLabel: 'Why this matters',
      itemsLabel: 'Priority investments',
      ctaLabel: 'Ask for the Full Funding Plan',
      ctaNote: 'Each phase’s full funding plan — budget, results framework and implementation timeline — is ready on request, for this phase alone or as a multi-year commitment across all four.',
      rows: [
        { label: 'Strengthen & scale · 0–12 months', meta: '₹25 lakh – ₹1 crore',
          obj: 'These investments build on proven models, deliver measurable outcomes quickly, and create the community foundations required for future innovation.',
          items: ['Expansion of AASs and community federations', "Women's leadership and community champions", 'Climate-adaptive agriculture and LEISA', 'Nutrition-sensitive agriculture and kitchen gardens', 'Farmer Resource Centres', 'Governance convergence and entitlement facilitation', 'Youth engagement and livelihood diversification'] },
        { label: 'Deepen innovation · 1–2 years', meta: '₹1 – 5 crore',
          obj: 'Innovation enables DEHAT to move beyond implementation by testing new models that respond to changing climate realities and emerging community needs.',
          items: ['Migration resilience', 'Institutional health assessment', "Women's leadership pathways", 'Youth climate leadership', 'Village resilience planning', 'Behavioural insights for climate adaptation', 'Climate risk mapping', 'Community knowledge management'] },
        { label: 'Build strategic systems · 3–5 years', meta: '₹5 – 15 crore',
          obj: 'These investments shift DEHAT from delivering programmes to building the infrastructure that allows communities and organisations to continuously understand, learn and respond to change.',
          items: ['Community Intelligence System', 'Landscape Intelligence', 'AI-assisted documentation and knowledge management', 'Participatory GIS and community mapping', 'Longitudinal resilience monitoring', 'Organisational learning systems', 'Decision-support tools for communities and grassroots teams'] },
        { label: 'Transform community resilience · 5–10 years', meta: '₹15 crore+',
          obj: 'These investments create public goods that extend beyond individual projects while positioning DEHAT as a national thought leader in community-centred climate resilience.',
          items: ['Community Intelligence Infrastructure', 'National resilience observatories', 'Longitudinal climate resilience research', 'AI-enabled adaptive planning', 'Landscape-scale resilience planning', 'National knowledge platform', 'Government partnerships and policy engagement'] },
      ],
    },

    close: {
      num: '06', // horizons restored as '05' (qualitative content only — see horizons.body/rows below)
      title: 'What makes the approach different',
      body: 'Many climate programmes focus primarily on improving agricultural outcomes. DEHAT’s experience suggests that resilience frequently breaks elsewhere: when nutrition remains weak, when community institutions dissolve, when women lack decision-making power, when governance systems remain inaccessible, or when migration disrupts local continuity.',
      chainLabel: 'Where most programmes stop',
      chainStop: 1,
      art: 'assets/cj/vine-trellis.png',
      arrows: [
        { from: 'Agriculture', to: 'A foundation for livelihoods' },
        { from: 'Livelihoods', to: 'Greater household stability' },
        { from: 'Stability', to: 'Leadership and collective action' },
        { from: 'Stronger institutions', to: 'Access to systems and opportunities' },
      ],
    },
  },

  re: {
    eyebrow: 'Programme journey',
    title: 'Rights exist. Realisation does not happen automatically.',
    body: 'India has an extensive architecture of rights, entitlements and public services. Rights are established through law and policy, while government programmes and public institutions provide the mechanisms through which people are expected to access them. But a right existing in law is only the starting point of its realisation. For a household, the distance between being entitled and actually experiencing that right can involve several stages, and at each stage a different barrier can intervene.',
    pull: 'The question is not how we help people access schemes. It is how people and communities come to understand what they are entitled to, navigate the systems that deliver it, act when access fails, sustain what they have gained, and collectively influence the institutions responsible.',
    chipsLabel: 'The journey as a progression in capability',
    chips: [
      'Recognise — this concerns a right',
      'Understand — what it means, who is responsible',
      'Navigate — the process and the requirements',
      'Claim — approach the institution',
      'Resolve — act when access is denied or delayed',
      'Sustain — hold access as circumstances change',
      'Enable others — rights capability as a community resource',
    ],

    cascade: {
      num: '01',
      title: 'Where the pathway from formal right to lived right breaks',
      body: 'These are not different versions of the same problem. They are different points at which the relationship between citizens and public systems can break down. Select a stage to see what stands in the way, and what the programme puts in its place.',
      colA: 'What can stand in the way',
      colB: 'What the programme builds',
      steps: [
        { label: 'Right → Capacity Building', img: T + 'right-participation.png',
          detail: 'Formal entitlement has limited value when people do not know it exists, or do not recognise their own eligibility for it.',
          a: 'Information gaps and social exclusion. Distance from institutions and unequal power within households determine who learns about a scheme and who remains outside it.',
          b: 'Rights knowledge carried through Child Parliaments, adolescent and youth groups, community leaders and local facilitators rather than one-off capacity-building sessions.' },
        { label: 'Capacity Building → Eligibility', img: T + 'issue-structural-vulnerability.png',
          detail: 'Knowing that something exists does not tell a person whether they qualify, or how to establish that qualification.',
          a: 'Eligibility sits behind documentation, administrative categories and unclear criteria. A person may satisfy the substantive conditions and still be unable to demonstrate them.',
          b: 'Practical understanding of eligibility, documents and institutional responsibility — rights knowledge made actionable.' },
        { label: 'Eligibility → Application', img: T + 'sdg-reduced-inequalities.png',
          detail: 'The problem shifts from information to navigation: where to go, which institution is responsible, what is required, how to follow up.',
          a: 'The more fragmented the system, the greater the burden placed on the individual to navigate it alone.',
          b: 'Navigation capability held locally — fellows, Community Resource Persons and community leaders who help households act.' },
        { label: 'Application → Access', img: T + 'sdg-partnership.png',
          detail: 'A submitted application does not guarantee access. Responsibility may sit across several frontline actors and departments.',
          a: 'Institutional delays, incomplete processing, exclusion and weak follow-up. A household often cannot know where a claim is stuck or who is responsible for resolving it.',
          b: 'Claim follow-up and escalation through community institutions, so the measure is what was received, not what was applied for.' },
        { label: 'Access → Sustained benefit', img: T + 'issue-bread-earner.png',
          detail: 'Benefits lapse. Documentation needs renewal. A family migrates. A child leaves school. A household becomes newly eligible for something else.',
          a: 'Continuity breaks when circumstances change, and a crisis resolved once can leave the conditions that produced it untouched.',
          b: 'Follow-up over time and institutional memory held in the community, rather than in a project cycle.' },
        { label: 'Individual problem → Collective action', img: T + 'sdg-peace.png',
          detail: 'When the same barrier is experienced repeatedly across households, it stops being an individual problem and becomes evidence of an institutional one.',
          a: 'Without organisation, credible evidence and access to decision-makers, recurring problems remain a collection of individual cases.',
          b: 'Aajeevika Adhikar Sangathans, federations and youth platforms that aggregate grievances and distinguish single cases from systemic barriers.' },
        { label: 'Collective claim → Institutional partnership', img: T + 'sdg-good-health.png',
          detail: 'Public systems may have several agencies responsible for parts of the same issue, so a claim can move between them without clear ownership.',
          a: 'Even when communities organise and present evidence, institutional response can remain weak or fragmented.',
          b: 'Institutional interfaces — Gram Panchayat, Block, Tehsil Diwas — used to place evidence in front of the institution that owns the decision.' },
      ],
    },

    tiers: {
      num: '02',
      title: 'Community institutions as the infrastructure of rights realisation',
      body: 'Rights are realised through interaction with institutions. Rather than creating a new structure for every issue or project, the programme works through a connected ecosystem of community platforms that develops across the life course. The significance of this architecture is not the existence of the groups. It is the capability they accumulate.',
      note: 'DEHAT does not build separate community structures for leadership, protection, climate justice and rights. The same people and institutions are strengthened through different programme investments; what changes is what we understand that institution to be enabling.',
      rows: [
        { label: 'Institutional response · working together', w: '100%', art: 'assets/story/entitlement-wheel-services.png',
          note: 'What becomes possible when evidence reaches the institution responsible for the decision.',
          items: ['Recurring barriers made visible', 'Grievances escalated with evidence', 'Representation at Gram Sabha and Tehsil Diwas', 'Departmental response tracked', 'Exclusion corrected at source'] },
        { label: 'Community institutions · collective capability', w: '74%', art: 'assets/story/entitlement-wheel.png',
          note: 'The platforms through which individual experience becomes collective evidence.',
          items: ['Child Parliaments', 'Adolescent and youth groups', 'Aajeevika Adhikar Sangathans and federations', 'VLCPCs and protection platforms', 'Fellows, CRPs and community leaders'] },
        { label: 'Rights-holders · individual capability', w: '92%', art: 'assets/story/entitlement-handover.png',
          note: 'Whether a rights-holder can recognise a right, understand eligibility, navigate the system, make a claim and seek help when it is blocked.',
          items: ['Rights and eligibility understood', 'Documents and pathways known', 'Claims made and followed up', 'Remedy sought when access fails', 'Participation in decisions that affect them'] },
      ],
    },

    toc: {
      num: '03',
      title: 'From rights capability to rights realisation',
      body: 'The goal is that individuals and communities increasingly understand, claim, protect and realise their rights and entitlements. Five pathways carry that goal, each moving capability one step further into institutional response.',
      fields: ['Community outcome', 'Ecosystem outcome', 'Critical enabler', 'Illustrative indicator'],
      paths: [
        { label: 'Capacity Building → Capability',
          detail: 'Rights-holders recognise rights, entitlements and the mechanisms available to them.',
          v: ['Greater capacity on rights, and knowledge of eligibility and mechanisms',
              'Community institutions identify recurring rights and entitlement gaps',
              'Accessible information, peer learning and participation',
              'Rights knowledge; knowledge of eligibility and responsible institutions'] },
        { label: 'Capability → Claim-making',
          detail: 'Individuals navigate systems and make claims; groups represent shared concerns.',
          v: ['Individuals increasingly navigate public systems and make claims',
              'Groups increasingly represent concerns and engage public institutions',
              'Leadership platforms, local facilitation and institutional linkages',
              'Claims initiated; participation; representations made'] },
        { label: 'Claim → Response',
          detail: 'Access to services, schemes, protections, public resources and justice mechanisms improves.',
          v: ['Improved access to services, schemes, protections and justice mechanisms',
              'Public institutions increasingly respond to organised community claims',
              'Institutional convergence, escalation, representation and follow-up',
              'Entitlements accessed; grievances resolved; institutional responses'] },
        { label: 'Resolution → Sustained realisation',
          detail: 'Access is held over time, and future barriers are met with capability already in place.',
          v: ['Rights-holders sustain access and respond to future barriers',
              'Community institutions retain knowledge and capacity for follow-up',
              'Institutional memory, local ownership and leadership continuity',
              'Sustained access; repeat claims; follow-up of unresolved issues'] },
        { label: 'Sustain → Enable others',
          detail: 'Accumulated experience becomes a community resource rather than an individual asset.',
          v: ['People with rights capability increasingly support others',
              'A wider pool of leaders, fellows, CRPs and peer actors sustains rights capability',
              'Mentoring, peer networks and leadership progression',
              'People supporting others; peer-led action; community-led facilitation'] },
      ],
    },

    pairs: {
      num: '04',
      title: 'From programme data to rights intelligence',
      body: 'Information about people, claims, institutions and outcomes can remain distributed across projects, reports, registers and individual staff memory. The next frontier is not more reporting. It is making community knowledge usable as intelligence — so that what is happening, who is affected, what action was taken and where systems are failing can be answered continuously. Select a row to see what the shift is intended to change.',
      colA: 'Today',
      colB: 'Future direction',
      colC: 'Intended outcome',
      artA: 'assets/cj/registers-desk.png',
      artB: 'assets/cj/community-planning-board.png',
      capA: 'Cases live in registers and individual memory. A recurring barrier looks like a series of unrelated households.',
      capB: 'Claims, responses and patterns are visible to the institutions that hold them, and to the people they describe.',
      rows: [
        { a: 'Information and processes may require navigating several people and institutions',
          b: 'Relevant rights, entitlements and next steps become easier to identify through trusted community channels',
          c: 'Greater ability to act independently, with less dependence on external facilitation.' },
        { a: 'Issues are identified, but case information and recurring barriers can remain fragmented',
          b: 'Community institutions can see patterns across households and track unresolved claims',
          c: 'Stronger collective claim-making, built on evidence rather than individual recollection.' },
        { a: 'Significant field time is spent collecting, documenting and repeatedly explaining the same information',
          b: 'Technology supports retrieval, navigation, documentation and follow-up',
          c: 'More time for facilitation and problem-solving, less for paperwork.' },
        { a: 'Learning remains distributed across projects and periodic reports',
          b: 'Rights-related information can be analysed across programmes and geographies',
          c: 'More adaptive programme design, informed by where claims actually fail.' },
        { a: 'Grievances reach institutions as separate cases',
          b: 'Community institutions present aggregated evidence of recurring barriers',
          c: 'Stronger evidence-based engagement with the department that owns the decision.' },
        { a: 'Strategic understanding depends substantially on periodic reporting and evaluation',
          b: 'Emerging claims, barriers, response patterns and institutional gaps become visible',
          c: 'Better strategic decisions about where capability and attention are needed.' },
        { a: 'Institutional learning remains distributed across people, projects and documents',
          b: 'Cases, solutions and institutional learning become searchable and reusable',
          c: 'The organisation gets stronger with each programme cycle rather than starting again.' },
      ],
    },

    horizons: {
      num: '05',
      title: 'A phased investment roadmap',
      body: 'The strategic opportunity is to strengthen the community institutions, claim-continuity systems, evidence infrastructure and technology through which rights can increasingly be realised and defended by communities themselves. Mapped in direct consultation with the communities we work with, over a planning process that ran from 2021 to 2026.',
      metaLabel: 'Indicative funding size',
      objLabel: 'Why this matters',
      itemsLabel: 'Priority investments',
      ctaLabel: 'Ask for the Full Funding Plan',
      ctaNote: 'Each phase’s full funding plan — budget, results framework and implementation timeline — is ready on request, for this phase alone or as a multi-year commitment across all four.',
      rows: [
        { label: 'Strengthen community capability · 0–18 months', meta: '₹25 lakh – ₹1 crore',
          obj: 'These investments strengthen the human infrastructure required for the next stage. Technology and systems only become useful when they sit inside community institutions capable of interpreting information and acting on it.',
          items: ['Strengthening AASs and community federations', 'Child Parliaments, adolescent and youth rights platforms', 'Community leaders, fellows, CRPs and peer facilitators', 'Entitlement navigation and facilitation', 'Community-level grievance identification and documentation', 'Rights and entitlement knowledge resources', 'Follow-up and escalation processes', 'Evidence capture across existing programmes'] },
        { label: 'Build claim continuity and evidence · 18 months–3 years', meta: '₹1 – 3 crore',
          obj: 'A stronger evidence architecture shows not only what communities receive, but where claims fail, why they fail, how communities respond and which institutional barriers recur.',
          items: ['Rights claim and case-continuity systems', 'Standardised claim and grievance documentation', 'Longitudinal tracking of selected entitlements', 'Community–institution follow-up mechanisms', 'Institutional response tracking', 'Cross-programme rights evidence', 'Research on barriers to rights realisation', 'Community-facing evidence and learning tools'] },
        { label: 'Build rights intelligence · 3–5 years', meta: '₹3 – 7 crore',
          obj: 'This is the transition from programme information to community intelligence. The objective is not another MIS, but an infrastructure that lets communities and DEHAT continuously understand rights demand, institutional response and recurring barriers.',
          items: ['Rights Intelligence System', 'Rights and entitlement knowledge base', 'Household-to-entitlement matching', 'Claim continuity and case tracking', 'Community-level rights dashboards', 'AI-assisted documentation and knowledge management', 'Multilingual and voice-enabled interfaces', 'Offline-first workflows', 'Organisational rights knowledge repository'] },
        { label: 'Demonstrate and scale · 5+ years', meta: '₹7 – 15 crore+',
          obj: 'At this stage the work moves beyond strengthening DEHAT’s own infrastructure towards a wider public good: evidence and models showing how community capability improves rights realisation and community–government partnership at scale.',
          items: ['Multi-geography rights intelligence infrastructure', 'Longitudinal rights-realisation research', 'Community Rights Observatories', 'Replication of successful community rights models', 'Cross-state learning networks', 'Public-system and government partnerships', 'Policy and systems research', 'Open knowledge resources where appropriate'] },
      ],
    },

    close: {
      num: '06', // horizons restored as '05' (qualitative content only — see horizons.body/rows below)
      title: 'What makes the approach different',
      body: 'Most rights work stops at access: an application made, a benefit received, a case closed. DEHAT’s experience suggests that realisation usually breaks after that point — when a benefit lapses, when the same barrier reappears in the next household, or when no institution owns the decision that produced the exclusion. Staying in partnership with the responsible institution is therefore not a layer added after access. It is part of what makes rights sustainable.',
      chainLabel: 'Where most rights work stops',
      chainStop: 1,
      art: 'assets/story/entitlement-girl-handover.png',
      arrows: [
        { from: 'Access', to: 'One household receives what is due' },
        { from: 'Aggregation', to: 'Repeated cases become one pattern' },
        { from: 'Evidence', to: 'The barrier can be named and located' },
        { from: 'Collective claim', to: 'The institution responsible is engaged' },
        { from: 'Institutional response', to: 'Exclusion corrected, recurrence reduced' },
      ],
    },
  },
};
