// Partnerships, engagement and investment — sitemap section 4.
// Bilingual. Every factual claim traces to finance-data.js or projects-data.js.

const EN = {
  eyebrow: 'Partnerships',
  title: 'Work with us.',
  sub: 'Every route below is one DEHAT can currently honour. Pick the one that fits, tell us what you have in mind, and the message writes itself.',

  tabs: [
    { k: 'route', label: 'Find Your Route' },
    { k: 'give', label: 'Invest' , detail: { u: "Field costs do not pause between grants. Regular investment is what keeps a team in place when a grant ends.", what: "A one-time or recurring investment, unrestricted or directed to a named programme.", why: "Unrestricted funds cover the gaps restricted grants leave: salaries between cycles, travel, follow-up on a case.", when: "Any time. Recurring investment is the most useful because it can be planned against.", where: "Domestic contributions into the 80G account; foreign contributions only into the designated FCRA account.", how: "Choose an amount and a purpose on this page; the receipt and statutory trail follow automatically." } },
    { k: 'people', label: 'Who We Work With' },
    { k: 'answer', label: 'Who We Answer To' },
  ],

  // ---- Step 1: who is asking ----
  whoTitle: 'First — who are you?',
  whoSub: 'This only decides what we show you next. Nothing is sent yet.',
  who: [
    { k: 'csr', label: 'A company or Corporate Social Responsibility team', hint: 'Schedule VII, Form CSR-1, due diligence' },
    { k: 'foundation', label: 'A foundation or institutional funder', hint: 'Multi-year, ecosystem or infrastructure' },
    { k: 'govt', label: 'Government or district administration', hint: 'Convergence, referral, field evidence' },
    { k: 'individual', label: 'An individual supporter', hint: 'Investing, occasions, ongoing support' },
    { k: 'research', label: 'A researcher or academic institution', hint: 'Field data, longitudinal study, co-publication' , detail: { u: "Two decades of field records exist. Every year they go unstudied is a year of evidence that stays unpublished.", what: "Co-designed research on a live programme, with access to field data and longitudinal records.", why: "Practice without study repeats itself. Study without practice generalises badly. The pairing corrects both.", when: "From the design stage, so measurement is built into the programme rather than fitted afterwards.", where: "Field sites in Bahraich and Shravasti, with records held at the DEHAT office.", how: "Send a concept note and your ethics position; we respond with what data exists, in what form, and on what terms." } },
    { k: 'student', label: 'A student or prospective colleague', hint: 'Fellowship, internship, career' },
    { k: 'school', label: 'A school', hint: 'Student engagement with peer children' },
    { k: 'peer', label: 'A peer organisation or network', hint: 'Consortium, referral, shared model' },
    { k: 'community', label: 'A community member', hint: 'Membership, a concern, a request' },
  ],

  // ---- Step 2: intent ----
  whatTitle: 'What would you like to do?',
  whatSub: 'Choose as many as apply.',
  intents: [
    { k: 'partner', label: 'Become a corporate or institutional partner', for: ['csr', 'foundation'], col: '#D2305C' , detail: { u: "Form CSR-1 filings and Schedule VII allocations are decided months before the financial year turns; the block plan you fund in April is written in January.", what: "A named, multi-year partnership on one programme in one geography, published in the project register with its own budget line.", why: "Fragmented one-year grants buy activity. Systems that keep working after a grant ends need a partner who stays for the horizon the change takes.", when: "Conversations that begin two quarters before your Corporate Social Responsibility cycle produce a first year that is planned rather than improvised.", where: "Bahraich and Shravasti in Uttar Pradesh, along the Indo-Nepal border, block by block.", how: "A scoping call, a due-diligence pack (12AB, 80G, CSR00001181, audited accounts with UDIN), a block plan, then a signed agreement." } },
    { k: 'consult', label: 'Adopt one of our models, or engage our Community Resource Persons', for: ['csr', 'govt', 'peer', 'foundation'], col: '#0E5565' , detail: { u: "Models sitting inside one district help one district. The same model handed to a peer helps a state.", what: "DEHAT’s field-tested rights-based models, and its Community Resource Persons, made available to your team.", why: "Building an approach from scratch costs years. Adapting one that already survived contact with the field costs months.", when: "Best before your own programme design is frozen, while the operating model can still absorb what the field teaches.", where: "On your sites, or in Bahraich where the models are running and can be observed in place.", how: "A structured walkthrough of the model, then an engagement letter covering Community Resource Person time, training and review." } },
    { k: 'converge', label: 'Work with us on district convergence or referral', for: ['govt', 'peer'], col: '#0E5565' , detail: { u: "A child intercepted at a border checkpost needs a referral route that already exists. It cannot be built during the interception.", what: "Joint working with district administration on convergence, referral and evidence between departments.", why: "Protection fails at the seams between systems, not inside them. Convergence closes the seams before a case falls through.", when: "Ahead of a district plan cycle, or immediately where a referral gap has already shown itself.", where: "District and block offices across Bahraich and Shravasti, and the seven border districts the work reaches.", how: "Write to us with the department and the gap; we bring the field evidence and a proposed referral protocol." } },
    { k: 'research', label: 'Become an academic research partner', for: ['research', 'foundation'], col: '#4F0E73' },
    { k: 'data', label: 'Request reports, audited accounts or programme data', for: ['csr', 'foundation', 'govt', 'research', 'peer', 'individual'], col: '#4F0E73' , detail: { u: "Anything published on this site can be traced to a signed document. Ask, and you get the document, not a summary.", what: "Audited accounts, evaluations, programme reports and the source records cited in the register.", why: "Trust that cannot be checked is not trust. Every claim here is meant to be verifiable by the person doubting it.", when: "Any time. Nothing here is embargoed and nothing waits on a funding conversation.", where: "Sent by email; originals available at the Bahraich office for anyone who wants to see them.", how: "Name the year, the programme or the document. If a figure is not yet digitised, we say so and send the scan." } },
    { k: 'visit', label: 'Arrange a field visit in Bahraich or Shravasti', for: ['csr', 'foundation', 'govt', 'research', 'student', 'peer', 'individual'], col: '#A92719' , detail: { u: "Distance makes this abstract. One day in a Gram Panchayat makes it impossible to unsee.", what: "A field visit to the villages, schools and Child Parliaments where the work actually happens.", why: "Reports compress. A visit restores what compression removes: the people, the terrain and the constraints.", when: "Any month outside the monsoon peak; we will tell you honestly which weeks the field is reachable.", where: "Bahraich and Shravasti, roughly six hours from Lucknow, closer from Nepalgunj.", how: "Send rough dates and headcount. We plan the route, arrange local logistics and tell you what to expect." } },
    { k: 'fellow', label: 'Become a DEHAT Fellow', for: ['student', 'research'], col: '#556223' , detail: { u: "A fellowship year spent close to a rights problem shapes a career more than a decade of describing one.", what: "A structured placement inside a programme, with real responsibility and a named supervisor.", why: "The sector needs people who have sat in a village meeting, not only people who have read about one.", when: "Cohorts follow the programme calendar; write early, since field placements are limited by supervision capacity.", where: "On site in Bahraich, with some functions partly remote.", how: "Tell us what you want to learn and what you can commit. We reply with what is open and what it demands." } },
    { k: 'intern', label: 'Intern or volunteer, on site or remotely', for: ['student', 'individual', 'school'], col: '#556223' , detail: { u: "Small, well-scoped contributions compound. Most of what a field team needs is finishable in weeks.", what: "A defined piece of work — field, research, documentation, design or translation — on site or remotely.", why: "Capacity is the binding constraint more often than money. An extra pair of hands moves a real deadline.", when: "Rolling. Remote work can start almost immediately; on-site placements need lead time.", where: "Bahraich, or anywhere with a connection for remote roles.", how: "Send your interest and availability; we match it against what is genuinely open rather than inventing a task." } },
    { k: 'career', label: 'Apply for a role', for: ['student', 'individual', 'peer'], col: '#556223' , detail: { u: "Field roles are filled by people who understood the work before they applied. That starts here.", what: "A paid role on the programme, operations, finance or documentation team.", why: "Long-term change needs staff who stay, not consultants who visit.", when: "When a vacancy is open. Interest sent between vacancies is kept and revisited.", where: "Mostly Bahraich; some roles are hybrid.", how: "Send what you would want to work on. We reply with what is open and what the role actually involves day to day." } },
    { k: 'member', label: 'Become a General Body member', for: ['community', 'individual', 'peer'], col: '#EAAE28' , detail: { u: "The General Body is where accountability is exercised, not observed.", what: "Membership of the General Body of DEHAT, the society’s governing membership.", why: "An organisation answerable only to its funders drifts. Members ask questions funders do not.", when: "Applications are considered against the society’s governance calendar.", where: "Registered office, Bahraich, Uttar Pradesh.", how: "Write with your reason for joining; the process and obligations are explained before you commit." } },
    { k: 'give', label: 'Invest once, or set up a regular investment', for: ['individual', 'community', 'school'], col: '#EAAE28' },
    { k: 'occasion', label: 'Host an event, or mark an occasion with us', for: ['individual', 'school', 'csr'], col: '#EAAE28' , detail: { u: "A birthday, an anniversary or a memorial redirected once can fund a whole cycle of one intervention.", what: "An occasion marked with DEHAT, or an event hosted in your city or campus.", why: "It converts a private moment into a public one and brings people to the work who would not otherwise arrive.", when: "Four to six weeks of notice lets us prepare material and, where possible, a voice from the field.", where: "Your venue, online, or in Bahraich.", how: "Tell us the occasion and the date; we handle the material, the receipts and the follow-up." } },
    { k: 'meet', label: 'Meet the people your support has reached', for: ['individual', 'csr', 'foundation'], col: '#D2305C' , detail: { u: "The distance between an investor and the person their money reached is usually never closed. It should be.", what: "A structured meeting — in person or online — with the people and communities your support reached.", why: "Accountability runs both ways. Seeing the outcome changes how the next decision is made.", when: "Arranged around the community’s calendar, never around the visitor’s convenience alone.", where: "In the villages themselves, or over a call where travel is not possible.", how: "Ask, and we arrange it with the consent of everyone who will be in the room." } },
    { k: 'workplace', label: 'Commit our workplace against child labour and child sexual abuse', for: ['csr', 'peer', 'school'], col: '#A92719' , detail: { u: "Child labour and child sexual abuse do not stop at your supply chain’s edge. A written commitment is where the audit starts.", what: "A workplace commitment against child labour and child sexual abuse, with the policy and training to hold it.", why: "A stated position gives employees a route to raise something they would otherwise stay quiet about.", when: "Before an incident, not after. Policy written under pressure protects nobody.", where: "Your workplace and its allied spaces — contractors, vendors, transport, housing.", how: "We share the model commitment, help adapt it, and train the people who will have to act on it." } },
    { k: 'schoolprog', label: 'Engage our students with children who have left school', for: ['school'], col: '#0E5565' , detail: { u: "A child who has left school is rarely brought back by an adult. They are brought back by another child.", what: "A structured engagement between your students and children who are out of school.", why: "Peer contact does what enrolment drives cannot: it makes returning feel ordinary rather than exceptional.", when: "Aligned to your academic calendar, with preparation before contact begins.", where: "Your school, and partner locations in Bahraich, connected online where distance requires it.", how: "We design the engagement with your teachers, brief both sets of children, and stay through the term." } },
    { k: 'fpo', label: 'Bulk-buy from Sondhi Maati Farmer Producer Company', for: ['csr', 'individual', 'peer', 'school'], col: '#556223' , detail: { u: "Every bulk order placed with the Farmer Producer Company is income that reaches a farmer without an intermediary taking a share.", what: "Bulk purchase from Sondhi Maati Farmer Producer Company, the farmer-owned company set up out of the Climate Justice work.", why: "Procurement is a more durable transfer than a donation, because it creates a customer rather than a recipient.", when: "Order against the harvest calendar; we will tell you what is available and when.", where: "Produced by women farmers in Bahraich; delivery arranged from there.", how: "Tell us quantities and timelines and we connect you directly to the company." } },
  ],

  // ---- Step 3: purpose + contact ----
  sopTitle: 'In a line or two — what are you hoping will change?',
  sopSub: 'This is the only part we read closely. Write it however you like; there is no right answer.',
  sopPlaceholder: 'For example: we want our Corporate Social Responsibility spend in Bahraich to go somewhere the evidence is public, and we would like to start with one block.',
  sopPrompts: [
    'What has brought you to this page today?',
    'Is there a place, an age group or an issue you already care about?',
    'What would make this worth your while a year from now?',
  ],
  fName: 'Your name', fOrg: 'Organisation (if any)', fEmail: 'Email', fPhone: 'Phone (optional)',
  fPlace: 'Where you are based (optional)', fBudget: 'Indicative scale, if you have one (optional)',
  budgets: ['Not decided yet', 'Under ₹5 lakh', '₹5–25 lakh', '₹25 lakh – ₹1 crore', 'Above ₹1 crore', 'Not a funding conversation'],

  reviewTitle: 'This is the message that will open in your email app.',
  reviewSub: 'Nothing is sent until you press send there. You can edit every word first.',
  send: 'Open in my email app',
  copy: 'Copy the message instead',
  copied: 'Copied',
  back: 'Back',
  next: 'Continue',
  step: 'Step',
  of: 'of',
  pickOne: 'Pick at least one to continue.',
  needName: 'Add a name and an email so we can reply.',

  // ---- Investing ----
  giveTitle: 'Invest',
  giveSub: 'Indian and foreign contributions are received into two separate accounts, under two separate registrations, because the law requires it. Choose the one that applies to you and the rest follows automatically.',
  regimes: [
    { k: 'inr', label: 'I am investing from India', note: '80G deduction available', detail: 'Received into the domestic account. An 80G receipt is issued against your PAN under registration AAAAD3793QF20241, valid to assessment year 2027–28. DEHAT also reports the donation in its Form 10BD statement, which is what lets you claim the deduction.', col: '#EAAE28' },
    { k: 'fcra', label: 'I am investing from outside India', note: 'Foreign Contribution (Regulation) Act 136260010', detail: 'Received only into the designated Foreign Contribution (Regulation) Act account at the State Bank of India, 11 Sansad Marg, New Delhi, as required by the Foreign Contribution (Regulation) Act. Foreign contributions do not carry an 80G deduction. A receipt and a utilisation statement are issued.', col: '#0E5565' },
  ],
  amountsInr: ['₹1,000', '₹2,500', '₹5,000', '₹10,000', '₹25,000', 'Other'],
  amountsFcra: ['$25', '$50', '$100', '$250', '$500', 'Other'],
  freqTitle: 'How often',
  freqs: [{ k: 'once', label: 'Once' }, { k: 'monthly', label: 'Every month' }, { k: 'yearly', label: 'Every year' }],
  purposeTitle: 'Where it should go',
  purposeNote: 'An unrestricted investment is the most useful kind. If you would rather direct it, the programme register shows exactly what each one funds.',
  purposes: [
    { k: 'unrestricted', label: 'Wherever it is needed most', note: 'Unrestricted' },
    { k: 'hp', label: 'Human Protection' },
    { k: 'cj', label: 'Climate Justice' },
    { k: 'sol', label: 'School of Leadership' },
    { k: 're', label: 'Rights and Entitlements' },
  ],
  idTitle: 'For your receipt',
  idNoteInr: 'The Income Tax Department requires a PAN against every 80G receipt, and DEHAT must report it in Form 10BD. Without it we can accept the investment but cannot issue a deduction certificate.',
  idNoteFcra: 'For foreign contributions DEHAT records the investor’s name, country and passport or national identity reference in its Foreign Contribution (Regulation) Act return. You can share it after the payment; it is not needed to invest.',
  fPan: 'PAN', fPanHint: 'Ten characters, as printed on the card',
  fIdCountry: 'Country', fIdRef: 'Passport or national ID number',
  fAddress: 'Address for the receipt',
  f80g: 'Issue me an 80G receipt',
  fAnon: 'Do not publish my name anywhere',
  dpNote: 'DEHAT collects only what the receipt and the statutory return require. Nothing here is stored in your browser, and nothing is shared with anyone outside the finance and audit process.',
  payNow: 'Continue to payment',
  paySafe: 'Payments are processed by Razorpay. DEHAT never sees your card or bank credentials.',
  payMissing: 'The payment gateway is not connected in this preview. Your selections are shown below so a developer can wire them to the correct Razorpay account.',
  payDomestic: 'Domestic Razorpay account · 80G · Form 10BD',
  payForeign: 'Foreign Contribution (Regulation) Act Razorpay account · State Bank of India, 11 Sansad Marg · Form FC-4 return',
  orEmail: 'Prefer a bank transfer, or investing in kind? Write to us and we will send account details.',

  // ---- Who We Work With ----
  peopleTitle: 'Who We Work With',
  peopleSub: 'Every organisation below appears because it appears in a signed agreement, an audited account or a published register on this site.',
  investorsTitle: 'Investment Partners',
  investorsSub: 'Institutions and companies whose funding is recorded against a named project in the register.',
  investorsFoot: 'Named funding bodies only. Implementation partners, referral institutions and government departments that appear in a project without a recorded contribution are named on that project\u2019s entry in the register instead. Where the archive does not establish who funded early work, the register says so rather than naming anyone here.',
  empanelTitle: 'Empanelments, Validation and Recognition',
  mediaTitle: 'In the Press',
  mediaSub: 'Independent coverage of the work. Links go to the publisher.',
  affilTitle: 'Networks and Consortiums',
  sisterTitle: 'Allied Institutions',
  sisters: [
    { k: 'Sondhi Maati Farmer Producer Company', v: 'A farmer-owned company set up out of the Climate Justice work, through which women farmers aggregate and sell.' },
    { k: 'Sondhi Maati LLP', v: 'The trading arm associated with the producer company.' },
    { k: 'RANG', v: 'The cultural and expression platform associated with DEHAT’s work with children and young people.' },
  ],
  affils: [
    { k: 'Campaign Against Child Labour (CACL)', v: 'DEHAT takes part in inter-country consultation platforms on cross-border standard operating procedures for restoration, rehabilitation and repatriation.' },
  ],
  mediaItems: [
    { pub: 'The Better India', title: 'Profile of DEHAT and its founder in Bahraich', href: 'https://thebetterindia.com/119495/dehat-jitendra-chaturvedi-bahraich/' },
    { pub: 'Down To Earth', title: 'Children, once again', href: 'https://www.downtoearth.org.in/environment/children-once-again-38301' },
    { pub: 'Deccan Herald', title: 'Coverage of the anti-trafficking work', href: 'https://www.deccanherald.com/features/he-risks-his-life-save-2223044' },
  ],

  // ---- Who We Answer To ----
  answerTitle: 'Who We Answer To',
  answerSub: 'The full governance chart, the annual accountability cycle and the open register of what we are not yet publishing sit on the Transparency page.',
  answerGo: 'Open the Transparency page',
};

const HI = {
  eyebrow: 'साझेदारी',
  title: 'हमारे साथ जुड़िए।',
  sub: 'नीचे दिया हर रास्ता वह है जिसे DEHAT आज निभा सकता है। जो आपके लिए सही हो चुनिए, अपनी बात बताइए, और संदेश अपने आप बन जाएगा।',

  tabs: [
    { k: 'route', label: 'अपना रास्ता चुनें' },
    { k: 'give', label: 'सहयोग करें' },
    { k: 'people', label: 'हमारे सहयोगी' },
    { k: 'answer', label: 'हम किसके प्रति उत्तरदायी हैं' },
  ],

  whoTitle: 'पहले — आप कौन हैं?',
  whoSub: 'इससे केवल यह तय होगा कि आगे क्या दिखेगा। अभी कुछ भेजा नहीं जा रहा।',
  who: [
    { k: 'csr', label: 'कंपनी या कॉर्पोरेट सामाजिक उत्तरदायित्व (CSR) टीम', hint: 'अनुसूची VII, फ़ॉर्म CSR-1, जाँच-पड़ताल' },
    { k: 'foundation', label: 'फ़ाउंडेशन या संस्थागत निवेशक', hint: 'बहुवर्षीय, तंत्र या अवसंरचना' },
    { k: 'govt', label: 'सरकार या ज़िला प्रशासन', hint: 'अभिसरण, संदर्भन, क्षेत्रीय प्रमाण' },
    { k: 'individual', label: 'व्यक्तिगत सहयोगी', hint: 'दान, अवसर, निरंतर सहयोग' },
    { k: 'research', label: 'शोधकर्ता या शैक्षणिक संस्थान', hint: 'क्षेत्रीय आँकड़े, दीर्घकालिक अध्ययन' },
    { k: 'student', label: 'विद्यार्थी या भावी सहकर्मी', hint: 'फ़ेलोशिप, इंटर्नशिप, नौकरी' },
    { k: 'school', label: 'विद्यालय', hint: 'विद्यार्थियों की सहभागिता' },
    { k: 'peer', label: 'सहयोगी संस्था या नेटवर्क', hint: 'कंसोर्टियम, संदर्भन, साझा मॉडल' },
    { k: 'community', label: 'समुदाय के सदस्य', hint: 'सदस्यता, कोई बात, कोई माँग' },
  ],

  whatTitle: 'आप क्या करना चाहेंगे?',
  whatSub: 'जितने लागू हों, उतने चुनिए।',
  intents: [
    { k: 'partner', label: 'कॉर्पोरेट या संस्थागत साझेदार बनें', for: ['csr', 'foundation'], col: '#D2305C' },
    { k: 'consult', label: 'हमारे मॉडल अपनाएँ, या सामुदायिक संसाधन व्यक्तियों से जुड़ें', for: ['csr', 'govt', 'peer', 'foundation'], col: '#0E5565' },
    { k: 'converge', label: 'ज़िला अभिसरण या संदर्भन पर साथ काम करें', for: ['govt', 'peer'], col: '#0E5565' },
    { k: 'research', label: 'शैक्षणिक शोध साझेदार बनें', for: ['research', 'foundation'], col: '#4F0E73' },
    { k: 'data', label: 'रिपोर्ट, अंकेक्षित लेखा या कार्यक्रम आँकड़े माँगें', for: ['csr', 'foundation', 'govt', 'research', 'peer', 'individual'], col: '#4F0E73' },
    { k: 'visit', label: 'बहराइच या श्रावस्ती में क्षेत्र भ्रमण तय करें', for: ['csr', 'foundation', 'govt', 'research', 'student', 'peer', 'individual'], col: '#A92719' },
    { k: 'fellow', label: 'DEHAT फ़ेलो बनें', for: ['student', 'research'], col: '#556223' },
    { k: 'intern', label: 'इंटर्न या स्वयंसेवक बनें, स्थल पर या दूरस्थ', for: ['student', 'individual', 'school'], col: '#556223' },
    { k: 'career', label: 'किसी पद के लिए आवेदन करें', for: ['student', 'individual', 'peer'], col: '#556223' },
    { k: 'member', label: 'साधारण सभा के सदस्य बनें', for: ['community', 'individual', 'peer'], col: '#EAAE28' },
    { k: 'give', label: 'सहयोग दें, या नियमित सहयोग शुरू करें', for: ['individual', 'community', 'school'], col: '#EAAE28' },
    { k: 'occasion', label: 'कार्यक्रम आयोजित करें, या कोई अवसर हमारे साथ मनाएँ', for: ['individual', 'school', 'csr'], col: '#EAAE28' },
    { k: 'meet', label: 'जिन तक आपका सहयोग पहुँचा, उनसे मिलें', for: ['individual', 'csr', 'foundation'], col: '#D2305C' },
    { k: 'workplace', label: 'अपने कार्यस्थल को बाल श्रम और बाल यौन शोषण से मुक्त रखने का संकल्प लें', for: ['csr', 'peer', 'school'], col: '#A92719' },
    { k: 'schoolprog', label: 'अपने विद्यार्थियों को विद्यालय छोड़ चुके बच्चों से जोड़ें', for: ['school'], col: '#0E5565' },
    { k: 'fpo', label: 'सोंधी माटी किसान उत्पादक कंपनी से थोक ख़रीद करें', for: ['csr', 'individual', 'peer', 'school'], col: '#556223' },
  ],

  sopTitle: 'एक-दो पंक्तियों में — आप क्या बदलते देखना चाहते हैं?',
  sopSub: 'हम इसी हिस्से को ध्यान से पढ़ते हैं। जैसे चाहें लिखिए; कोई सही उत्तर नहीं है।',
  sopPlaceholder: 'उदाहरण: हम चाहते हैं कि बहराइच में हमारा कॉर्पोरेट सामाजिक उत्तरदायित्व व्यय वहाँ जाए जहाँ प्रमाण सार्वजनिक हों, और एक ब्लॉक से शुरुआत करें।',
  sopPrompts: [
    'आज आप इस पृष्ठ तक किस कारण पहुँचे?',
    'कोई जगह, आयु वर्ग या मुद्दा जिसकी आपको पहले से चिंता है?',
    'एक साल बाद इसे सार्थक क्या बनाएगा?',
  ],
  fName: 'आपका नाम', fOrg: 'संस्था (यदि हो)', fEmail: 'ईमेल', fPhone: 'फ़ोन (वैकल्पिक)',
  fPlace: 'आप कहाँ से हैं (वैकल्पिक)', fBudget: 'अनुमानित परिमाण, यदि तय हो (वैकल्पिक)',
  budgets: ['अभी तय नहीं', '₹5 लाख से कम', '₹5–25 लाख', '₹25 लाख – ₹1 करोड़', '₹1 करोड़ से अधिक', 'यह वित्तीय बातचीत नहीं है'],

  reviewTitle: 'यही संदेश आपके ईमेल ऐप में खुलेगा।',
  reviewSub: 'जब तक आप वहाँ भेजें नहीं, कुछ नहीं जाता। हर शब्द पहले बदल सकते हैं।',
  send: 'मेरे ईमेल ऐप में खोलें',
  copy: 'संदेश कॉपी करें',
  copied: 'कॉपी हो गया',
  back: 'पीछे',
  next: 'आगे',
  step: 'चरण',
  of: '/',
  pickOne: 'आगे बढ़ने के लिए कम से कम एक चुनें।',
  needName: 'उत्तर देने के लिए नाम और ईमेल जोड़ें।',

  giveTitle: 'सहयोग करें',
  giveSub: 'भारतीय और विदेशी अंशदान दो अलग खातों में, दो अलग पंजीकरणों के अंतर्गत प्राप्त होते हैं, क्योंकि क़ानून यही अपेक्षा करता है। जो आप पर लागू हो चुनिए, बाक़ी अपने आप हो जाएगा।',
  regimes: [
    { k: 'inr', label: 'मैं भारत से दे रहा/रही हूँ', note: '80G छूट उपलब्ध', detail: 'घरेलू खाते में प्राप्त। आपके PAN पर पंजीकरण AAAAD3793QF20241 के अंतर्गत 80G रसीद जारी होती है, जो निर्धारण वर्ष 2027–28 तक वैध है। DEHAT इसे फ़ॉर्म 10BD विवरण में भी दर्ज करता है, जिससे आप छूट का दावा कर पाते हैं।', col: '#EAAE28' },
    { k: 'fcra', label: 'मैं भारत के बाहर से दे रहा/रही हूँ', note: 'Foreign Contribution (Regulation) Act 136260010', detail: 'विदेशी अंशदान (विनियमन) अधिनियम के अनुसार केवल भारतीय स्टेट बैंक, 11 संसद मार्ग, नई दिल्ली के निर्दिष्ट FCRA खाते में प्राप्त। विदेशी अंशदान पर 80G छूट नहीं मिलती। रसीद और उपयोग विवरण जारी किए जाते हैं।', col: '#0E5565' },
  ],
  amountsInr: ['₹1,000', '₹2,500', '₹5,000', '₹10,000', '₹25,000', 'अन्य'],
  amountsFcra: ['$25', '$50', '$100', '$250', '$500', 'अन्य'],
  freqTitle: 'कितनी बार',
  freqs: [{ k: 'once', label: 'एक बार' }, { k: 'monthly', label: 'हर महीने' }, { k: 'yearly', label: 'हर वर्ष' }],
  purposeTitle: 'कहाँ लगे',
  purposeNote: 'अनिर्दिष्ट सहयोग सबसे उपयोगी होता है। यदि आप दिशा तय करना चाहें, तो कार्यक्रम पंजी में हर कार्यक्रम का ब्यौरा है।',
  purposes: [
    { k: 'unrestricted', label: 'जहाँ सबसे ज़्यादा ज़रूरत हो', note: 'अनिर्दिष्ट' },
    { k: 'hp', label: 'मानव संरक्षण' },
    { k: 'cj', label: 'जलवायु न्याय' },
    { k: 'sol', label: 'नेतृत्व विद्यालय' },
    { k: 're', label: 'अधिकार और हक़' },
  ],
  idTitle: 'आपकी रसीद के लिए',
  idNoteInr: 'आयकर विभाग हर 80G रसीद पर PAN अनिवार्य करता है, और DEHAT को इसे फ़ॉर्म 10BD में दर्ज करना होता है। इसके बिना हम सहयोग स्वीकार कर सकते हैं पर छूट प्रमाणपत्र जारी नहीं कर सकते।',
  idNoteFcra: 'विदेशी अंशदान के लिए DEHAT अपनी विदेशी अंशदान (विनियमन) अधिनियम विवरणी में दाता का नाम, देश और पासपोर्ट या राष्ट्रीय पहचान संदर्भ दर्ज करता है। यह भुगतान के बाद भी दिया जा सकता है; देने के लिए आवश्यक नहीं।',
  fPan: 'PAN', fPanHint: 'दस अक्षर, जैसे कार्ड पर छपे हैं',
  fIdCountry: 'देश', fIdRef: 'पासपोर्ट या राष्ट्रीय पहचान संख्या',
  fAddress: 'रसीद के लिए पता',
  f80g: 'मुझे 80G रसीद चाहिए',
  fAnon: 'मेरा नाम कहीं प्रकाशित न करें',
  dpNote: 'DEHAT केवल वही जानकारी लेता है जो रसीद और वैधानिक विवरणी के लिए आवश्यक है। यहाँ कुछ भी आपके ब्राउज़र में संग्रहित नहीं होता, और वित्त व अंकेक्षण प्रक्रिया के बाहर किसी से साझा नहीं होता।',
  payNow: 'भुगतान पर जाएँ',
  paySafe: 'भुगतान Razorpay द्वारा संसाधित होते हैं। DEHAT आपके कार्ड या बैंक विवरण कभी नहीं देखता।',
  payMissing: 'इस पूर्वावलोकन में भुगतान गेटवे जुड़ा नहीं है। आपके चयन नीचे दिखाए गए हैं ताकि डेवलपर उन्हें सही Razorpay खाते से जोड़ सके।',
  payDomestic: 'घरेलू Razorpay खाता · 80G · फ़ॉर्म 10BD',
  payForeign: 'विदेशी अंशदान (विनियमन) अधिनियम Razorpay खाता · भारतीय स्टेट बैंक, 11 संसद मार्ग · फ़ॉर्म FC-4 विवरणी',
  orEmail: 'बैंक हस्तांतरण या वस्तु-रूप में देना चाहेंगे? हमें लिखिए, हम खाता विवरण भेज देंगे।',

  peopleTitle: 'हमारे सहयोगी',
  peopleSub: 'नीचे हर संस्था इसलिए है क्योंकि वह किसी हस्ताक्षरित अनुबंध, अंकेक्षित लेखे या इस साइट की प्रकाशित पंजी में दर्ज है।',
  investorsTitle: 'निवेश साझेदार',
  investorsSub: 'वे संस्थाएँ और कंपनियाँ जिनका अनुदान पंजी में किसी नामित परियोजना के सामने दर्ज है।',
  investorsFoot: 'केवल नामित वित्तपोषक संस्थाएँ। क्रियान्वयन साझेदार, संदर्भन संस्थान और सरकारी विभाग, जिनका कोई दर्ज अंशदान नहीं है, उनका नाम संबंधित परियोजना की प्रविष्टि में है। जहाँ अभिलेख से यह स्थापित नहीं होता कि आरंभिक कार्य किसने वित्तपोषित किया, वहाँ पंजी यही कहती है, किसी का नाम नहीं देती।',
  empanelTitle: 'सूचीबद्धता, सत्यापन और सम्मान',
  mediaTitle: 'समाचारों में',
  mediaSub: 'कार्य पर स्वतंत्र कवरेज। लिंक प्रकाशक तक ले जाते हैं।',
  affilTitle: 'नेटवर्क और कंसोर्टियम',
  sisterTitle: 'संबद्ध संस्थाएँ',
  sisters: [
    { k: 'सोंधी माटी किसान उत्पादक कंपनी', v: 'जलवायु न्याय कार्य से बनी किसानों की अपनी कंपनी, जिसके ज़रिए महिला किसान एकत्रित होकर बिक्री करती हैं।' },
    { k: 'सोंधी माटी LLP', v: 'उत्पादक कंपनी से जुड़ी व्यापारिक इकाई।' },
    { k: 'RANG', v: 'बच्चों और युवाओं के साथ DEHAT के कार्य से जुड़ा सांस्कृतिक और अभिव्यक्ति मंच।' },
  ],
  affils: [
    { k: 'बाल श्रम विरोधी अभियान (CACL)', v: 'DEHAT पुनर्स्थापन, पुनर्वास और प्रत्यावर्तन की सीमा-पार मानक संचालन प्रक्रियाओं पर अंतर-देशीय परामर्श मंचों में भाग लेता है।' },
  ],
  mediaItems: [
    { pub: 'The Better India', title: 'बहराइच में DEHAT और उसके संस्थापक पर आलेख', href: 'https://thebetterindia.com/119495/dehat-jitendra-chaturvedi-bahraich/' },
    { pub: 'Down To Earth', title: 'Children, once again', href: 'https://www.downtoearth.org.in/environment/children-once-again-38301' },
    { pub: 'Deccan Herald', title: 'तस्करी-विरोधी कार्य पर कवरेज', href: 'https://www.deccanherald.com/features/he-risks-his-life-save-2223044' },
  ],

  answerTitle: 'हम किसके प्रति उत्तरदायी हैं',
  answerSub: 'पूरा शासन चार्ट, वार्षिक जवाबदेही चक्र और जो अभी प्रकाशित नहीं है उसकी खुली पंजी — सब पारदर्शिता पृष्ठ पर हैं।',
  answerGo: 'पारदर्शिता पृष्ठ खोलें',
};

export const PARTNER = { en: EN, hi: HI };
