// Turning points in DEHAT's history, 1968–2026.
export const ERAS = [
  { k: 'e1', label: 'Before DEHAT had a name', span: '1968\u20131988', art: 't-pair-a.png',
    note: 'A childhood in West Champaran, and the hunger that set the terms for everything after it.' },
  { k: 'e2', label: 'Bichhia, unregistered', span: '1989\u20131999', art: 't-family.png',
    note: 'A doctor who charged nothing, Vananchal, a school with no building, and a youth group with no registration number.' },
  { k: 'e3', label: 'The Institution', span: '2000\u20132009', art: 't-four.png',
    note: 'A society on paper, a study of the forest villages, and a movement the forest dependent communities ran themselves.' },
  { k: 'e4', label: 'System, movement, recognition', span: '2010\u20132020', art: 't-crowd.png',
    note: 'Land titles won, RTIs filed by women, children brought back across the border, and awards that went to the community.' },
  { k: 'e5', label: 'Rupture and Rebuild', span: '2021\u20132026', art: 't-sprig.png',
    note: 'A death with no succession plan, and the years of redesign that followed it.' },
];

export const REGISTER = [
  { id: 'E001', era: 'e1', year: '1968', sort: 1968, lane: 'person', who: 'Jitendra Chaturvedi', place: 'Khairwa, West Champaran, Bihar',
    title: 'A Boy is born in Champaran',
    story: 'Jitendra Chaturvedi was born on 19 December 1968 in Khairwa, West Champaran \u2014 the Bihar countryside that had drawn Gandhi to his first satyagraha half a century earlier.' },
  { id: 'E002', era: 'e1', year: '1973\u201376', sort: 1973, lane: 'person', who: 'Jitendra Chaturvedi', place: 'The family home',
    title: 'The Family is put out of the House',
    story: 'His father vanished after a dispute, and the prosperous joint family around them closed ranks. His mother and her children were sent out of the house to live in a cowshed. What followed was hunger of the ordinary, daily kind, the sort that leaves no record anywhere.' },
  { id: 'E003', era: 'e1', year: '1973\u201376', sort: 1973.1, lane: 'person', who: 'The family', place: 'The family home',
    title: 'The Nights without a Moon',
    story: 'Food was looked for after midnight: potatoes missed by the harvesters, pumpkins left drying on rooftops. Full-moon nights were avoided. On those nights you could be seen.' },
  { id: 'E004', era: 'e1', year: '1973\u201376', sort: 1973.2, lane: 'person', who: 'The family', place: 'The family home',
    title: 'Water from the Cattle Vessels',
    story: 'Clean water was not shared with them. They drew what they needed from the vessels the cattle drank from, then boiled it and filtered it before anyone in the house would drink.' },
  { id: 'E005', era: 'e1', year: '1970s\u201380s', sort: 1975, lane: 'person', who: 'Jitendra Chaturvedi', place: 'Hisar and Bahraich',
    title: 'A Child Labourer pays his own School Fees',
    story: 'He worked as a child labourer and a domestic servant to keep himself in school, and made stationery out of discarded paper to sell on the side. Hunger was hidden through the school day and met again at night.' },
  { id: 'E006', era: 'e1', year: '1976', sort: 1976, lane: 'person', who: 'The family', place: 'Bahraich',
    title: 'The Father returns, and the Family moves to Bahraich',
    story: 'In January 1976 his father came back and moved the family to Bahraich, on the Nepal border. Everything that follows in this history happens within a day\u2019s travel of that town.' },
  { id: 'E009', era: 'e1', year: '1989/90', sort: 1988, lane: 'person', who: 'Jitendra Chaturvedi', place: 'Kanpur',
    title: 'He trains as a Homoeopath',
    story: 'He qualified in homoeopathy at Kanpur and later took an MA in Sociology. Medicine is what first put him in a room with other people\u2019s suffering and gave him a reason to be trusted there.' },
  { id: 'E010', era: 'e1', year: 'Late 1980s', sort: 1988.5, lane: 'person', who: 'Jitendra Chaturvedi', place: 'India',
    title: 'Turned down on Medical Grounds',
    story: 'He applied to the Indian Air Force and was rejected at the medical. The family has always read the rejection as the childhood hunger returning to close a door, years after the hunger itself had ended \u2014 the Air Force turned him down, but what disqualified him was the malnutrition.' },

  { id: 'E011', era: 'e2', year: '1989\u201390', sort: 1989, lane: 'person', who: 'Jitendra Chaturvedi', place: 'Bichhia, Bahraich', prog: 'Human Protection',
    title: 'The Doctor moves to the Forest',
    story: 'He and his wife moved to Bichhia, at the edge of the Katarniaghat forest, and lived in a thatched house. Most of his patients were forest-dwelling families who could not find fifty paise, let alone a rupee. He treated them anyway, and the practice never became a living.' },
  { id: 'E012', era: 'e2', year: '1989\u201393', sort: 1989.1, lane: 'person', who: 'His wife', place: 'Bichhia, Bahraich',
    title: 'The Partnership behind the Public Life',
    story: 'She carried the household, the money and the uncertainty of a thatched house in a forest region. It was not occasional support. It remained the private infrastructure of his public life for the next thirty-two years.' },
  { id: 'E013', era: 'e2', year: '1989\u201393', sort: 1989.2, lane: 'person', who: 'Jitendra Chaturvedi', place: 'Bahraich', prog: 'School of Leadership',
    title: 'Songs pay for the Free Clinic',
    story: 'To feed his own family while treating everyone else for nothing, he wrote, composed and sang folk songs at the gatherings of better-off households. The clinic in the forest was, for several years, funded by singing.' },
  { id: 'E014', era: 'e2', year: '1989\u201393', sort: 1989.3, lane: 'community', who: 'The youth group', place: 'Bichhia', prog: 'School of Leadership',
    title: 'Theatre, Sport and Song gather the Young',
    story: 'Long before he had any vocabulary of development practice, he had performance and sport. A volleyball match brought young men out; a street play kept them there. Between the two, local injustice became something that could be said out loud in public.' },
  { id: 'E015', era: 'e2', year: '1989\u201393', sort: 1989.4, lane: 'person', who: 'Jitendra Chaturvedi', place: 'Bahraich and Mumbai',
    title: 'A Writing Career he could not afford',
    story: 'His writing drew interest from the film industry. The fare, the food and the lodging between Bahraich and Mumbai were beyond him, so the scripts stayed where they were written and turned into street plays and songs instead.' },
  { id: 'E016', era: 'e2', year: '1989\u201393', sort: 1989.5, lane: 'community', who: 'Forest children', place: 'Bichhia', prog: 'Human Protection',
    title: 'Vananchal, The First School',
    story: 'A school opened for Tharu and other forest-dwelling children, run out of the same youth group. It was named Vananchal. There was no building and no registration. This is the year DEHAT counts as its beginning, eleven years before it existed on paper. Vananchal is still running, now looked after by Shahid Ali.' },
  { id: 'E017', era: 'e2', year: 'c.1991\u201393', sort: 1991, lane: 'person', who: 'Jitendra Chaturvedi', place: 'Bichhia',
    title: 'Handcuffed through the Bazaar',
    story: 'After he crossed local interests he was detained, walked through the bazaar in handcuffs and held for five days. The school was destroyed while he was inside and most of the youth group scattered. Thirty years later the same lesson would arrive again: work held by one person can be stopped by removing that person.' },
  { id: 'E018', era: 'e2', year: '1992\u20132002', sort: 1992, lane: 'person', who: 'Jitendra Chaturvedi', place: 'Districts across Uttar Pradesh', prog: 'Maternal and Child Health',
    title: 'Ten Years learning somebody else\u2019s Trade',
    story: 'He left Bichhia and spent a decade inside voluntary, Gandhian and international health organisations. He came back with method for an instinct he already had: how to run participation, training, documentation and a project that survives an audit.' },

  { id: 'E019', era: 'e3', year: '2000', sort: 2000, lane: 'dehat', who: 'DEHAT', place: 'Bahraich', prog: 'All',
    title: 'DEHAT is registered',
    story: 'On 21 August 2000, the Developmental Association for Human Advancement became a registered society under the Societies Registration Act. The work it was registering was already eleven years old.' },
  { id: 'E020', era: 'e3', year: '2002\u201303', sort: 2002, lane: 'dehat', who: 'DEHAT', place: 'Eight forest villages', prog: 'Rights and Entitlements',
    title: 'Slave Forest Villages in Independent India',
    story: 'Before any campaign, a study. Eight settlements on the banks of Katarniaghat turned out to be missing from revenue and panchayat records altogether: no certificates, no ration access, no secure land, and labour arrangements the residents themselves described as coercive. Hindustan Times and Suchna Express carried it. The state\u2019s answer was that these people were encroachers.' },
  { id: 'E021', era: 'e3', year: '2003\u201305', sort: 2003, lane: 'community', who: 'Vangram Adhikar Manch', place: 'The forest villages', prog: 'Rights and Entitlements',
    title: 'A Movement built to belong to the Forest Dependent Communities',
    story: 'Membership of the Manch was open only to affected residents, which meant DEHAT could not vote in it. Cadres were trained from among the villagers, families paid into a small Gram Kosh, and \u201cJai Azaadi\u201d became the greeting between them \u2014 crossing caste and religion, in a place where neither usually gives way.' },
  { id: 'E023', era: 'e3', year: '2005\u201306', sort: 2005, lane: 'dehat', who: 'DEHAT', place: 'New Delhi', prog: 'Rights and Entitlements',
    title: 'Submissions on the Forest Rights Bill',
    story: 'While the forest-rights law was being drafted, recommendations from the villages went to the Joint Parliamentary Committee, asking that traditional forest dwellers who are not Scheduled Tribes be included. The final Act includes them. We took part in the advocacy; we have never claimed the clause.' },
  { id: 'E024', era: 'e3', year: '2006', sort: 2006, lane: 'community', who: 'Forest communities', place: 'Bichhia Bazar', prog: 'Rights and Entitlements',
    title: 'Forest Dependent Communities ask to be counted as Citizens',
    story: 'Residents of the forest villages came into Bichhia bazar and demonstrated, not for a scheme or a subsidy, but to be recognised as citizens and given the ordinary rights that follow from it.' },
  { id: 'E029', era: 'e3', year: '2007', sort: 2007, lane: 'community', who: 'Children', place: 'Bahraich', prog: 'Human Protection',
    title: 'A thousand Children march for Schools',
    story: 'Around a thousand children walked through Bahraich to demand schools and anganwadi centres in their own villages, rather than in the villages they were expected to walk to.' },
  { id: 'E030', era: 'e3', year: '2008', sort: 2008, lane: 'community', who: 'Forest communities', place: 'Motipur and Bahraich', prog: 'Rights and Entitlements',
    title: 'Nyaya Adhikaar Satyagrah',
    story: 'Cases had been filed against 123 villagers. The answer was a march, a hunger strike, a mass surrender by the accused, and chulha bandi \u2014 evening stoves left unlit across the settlements, so that the hunger was visible and chosen rather than hidden.' },
  { id: 'E031', era: 'e3', year: '2009', sort: 2009, lane: 'person', who: 'Jitendra Chaturvedi', place: 'Bengaluru', prog: 'Rights and Entitlements', award: true,
    title: 'The Manjunath Shanmugam Integrity Award',
    story: 'Aruna Roy presented the award, given in memory of an IIM graduate and Indian Oil officer shot dead for refusing to let fuel adulteration pass. It was shared with Vinod Adhau and Sanjiv Chaturvedi. The prize money went straight into the forest-village struggle.',
    links: [
      { label: 'Indian Express \u2014 the shortlist', href: 'https://indianexpress.com/article/news-archive/web/manjunath-award-vidarbha-officer-conservator-activist-shortlisted/lite/' },
      { label: 'Times of India \u2014 candle-light march in memory of Manjunath', href: 'https://timesofindia.indiatimes.com/city/lucknow/candle-light-march-in-memory-of-manjunath/articleshow/6956970.cms' },
    ] },

  { id: 'E033', era: 'e4', year: '2010', sort: 2010, lane: 'community', who: 'Gokulpur', place: 'Dafedaar Gaudi, Bahraich', prog: 'Rights and Entitlements',
    title: 'A Forest Village becomes a Revenue Village',
    story: 'Dafedaar Gaudi was renamed Gokulpur and reported as the first village in Uttar Pradesh converted under the Forest Rights Act. Fifty-three families received title over 25.839 hectares \u2014 the first time any of them held paper for the ground they lived on.' },
  { id: 'E035', era: 'e4', year: '2010\u201311', sort: 2010.5, lane: 'dehat', who: 'DEHAT', place: 'New Delhi', prog: 'All', award: true,
    title: 'India NGO Award',
    story: 'Joint winner in the small-organisation category, judged by the Resource Alliance and the Rockefeller Foundation on governance, transparency, fundraising and results rather than on story.' },
  { id: 'E037', era: 'e4', year: '2011\u201312', sort: 2011, lane: 'community', who: 'Women of the forest villages', place: 'The forest villages', prog: 'Rights and Entitlements',
    title: 'Fifty-two Women ask for the Order in writing',
    story: 'Thirteen RTI applications asked the departments to produce the order that supposedly kept these villages outside the system. No such order existed, and no department could produce one. Women who had spent their lives being described as beneficiaries were now investigating the state, and winning.',
    links: [{ label: 'Women and RTI power \u2014 DEHAT', href: 'https://dehatindia.org/stories-of-change/women-and-rti-power/' }] },
  { id: 'E038', era: 'e4', year: '2012', sort: 2012, lane: 'person', who: 'Jitendra Chaturvedi', place: 'Mumbai', prog: 'Rights and Entitlements', award: true,
    title: 'CID Veerta Social Bravery Award',
    story: 'Named a winner in the social-bravery category for those above fifteen, twenty years after the five days in the Bichhia lock-up.' },
  { id: 'E039', era: 'e4', year: '2013', sort: 2013, lane: 'dehat', who: 'DEHAT', place: 'Bahraich to Kathmandu', prog: 'Human Protection',
    title: 'Seven Children come home from Kathmandu',
    story: 'Seven Bahraich children in bonded work in Nepal were traced and brought back. It took police on both sides of an open border, child-welfare officers, lawyers and Nepali organisations agreeing to move at the same time \u2014 the first proof that the border could be worked rather than only mourned.' },
  { id: 'E042', era: 'e4', year: '2014\u201315', sort: 2014, lane: 'dehat', who: 'DEHAT', place: 'The Indo\u2013Nepal border', prog: 'Human Protection',
    title: 'A Border becomes a Protection System',
    story: 'Booths at the crossing points, rescues coordinated across two jurisdictions, cases entered into the government database, and training for police and paramilitary personnel who had never once been asked to think about children.' },
  { id: 'E046', era: 'e4', year: '2015', sort: 2015, lane: 'dehat', who: 'DEHAT', place: 'Bahraich', prog: 'Human Protection',
    title: 'After the Nepal Earthquake',
    story: 'Traffickers move towards disasters. Within weeks of the earthquake we handed district authorities a list of seventeen suspects, and the police and the Sashastra Seema Bal tightened the crossings while the aid was still going the other way.' },
  { id: 'E050', era: 'e4', year: '2015', sort: 2015.5, lane: 'community', who: 'Sunita and eleven others', place: 'Lucknow', prog: 'Human Protection', award: true,
    title: 'Twelve Adolescents take the Swayam Awards',
    story: 'On 2 December 2015 the Chief Minister of Uttar Pradesh gave the Swayam Awards to twelve adolescents from across the state. Among them was Sunita, who had held out through eight hours of pressure to get a case registered that the local station officer had refused to touch.',
    links: [{ label: 'Swayam Awards ceremony \u2014 video', href: 'https://www.youtube.com/watch?v=dl-sTaUfMDI' }] },
  { id: 'E047', era: 'e4', year: '2016', sort: 2016, lane: 'community', who: 'Bhanumati', place: 'New Delhi', prog: 'School of Leadership', award: true,
    title: 'Bhanumati is honoured at Rashtrapati Bhavan',
    story: 'The President named her one of India\u2019s hundred women achievers, for her work against child marriage, against addiction, and against theft in the ration system. The award is hers. We were in the room.' },
  { id: 'E048', era: 'e4', year: '2016', sort: 2016.1, lane: 'community', who: 'Rekha', place: 'Lucknow', prog: 'Human Protection', award: true,
    title: 'Rekha receives the Rani Lakshmi Bai Award',
    story: 'Uttar Pradesh honoured her for leadership against trafficking, including the night she helped stop a child being taken towards the Nepal border.' },
  { id: 'E057', era: 'e4', year: '2020\u201321', sort: 2020, lane: 'community', who: 'Gudiya', place: 'Dhakia Kailash Nagar', prog: 'Climate Justice',
    title: 'A landless Woman farms through the Lockdown',
    story: 'When her husband lost his work, Gudiya leased one and a half bighas and planted vegetables with seed from the Suposhan programme. She cleared \u20b965,000 over the year and put \u20b925,000 of it into a buffalo calf. She is the protagonist of that story; we supplied the seed.' },

  { id: 'E058', era: 'e5', year: '5 May 2021', sort: 2021, lane: 'person', who: 'Jitendra Chaturvedi', place: 'Bahraich',
    title: 'The Founder dies in the Second Wave',
    story: 'He died of COVID-19 at Bahraich Medical College. There was no handover, no succession plan and no second signature. Teams were grieving while child-protection emergencies, salaries, reports and promises to villages went on arriving as though nothing had happened.' },
  { id: 'E059', era: 'e5', year: 'June 2021', sort: 2021.1, lane: 'person', who: 'Devyani Chaturvedi', place: 'Bahraich', prog: 'All',
    title: 'Devyani takes over as Executive Director',
    story: 'She stepped into an organisation whose founder had been father, mentor, decision-maker and living archive, with Divyanshu carrying operations beside her. Succession inside a family raises fair questions about authority and independence. They were asked, and they should have been.' },
  { id: 'E060', era: 'e5', year: '2021\u201322', sort: 2021.2, lane: 'dehat', who: 'DEHAT', place: 'Bahraich', prog: 'All',
    title: 'Holding it together',
    story: 'The first year was continuity and nothing more ambitious: keep the staff, keep talking to partners, keep the projects legal, stay present in the villages. The harder work was saying out loud how much of this had depended on one man.' },
  { id: 'E061', era: 'e5', year: '2022\u201324', sort: 2022, lane: 'dehat', who: 'DEHAT', place: 'National', prog: 'All', award: true,
    title: 'Into the GROW Cohort',
    story: 'EdelGive picked DEHAT into a national cohort of a hundred organisations for flexible core funding and organisational support. It was not a prize. It was an investment in whether we would still exist in three years.',
    links: [{ label: 'Business Standard \u2014 the cohort of 100 is announced', href: 'https://www.business-standard.com/content/press-releases-ani/edelgive-foundation-s-grow-fund-announces-its-cohort-of-100-ngo-grantees-122012100997_1.html' }] },
  { id: 'E062', era: 'e5', year: '2022\u201324', sort: 2022.1, lane: 'dehat', who: 'DEHAT', place: 'Bahraich', prog: 'All',
    title: 'The Fund says it prevented a Shutdown',
    story: 'In its own book, EdelGive writes that the support stopped DEHAT closing, kept skilled staff in place, and rebuilt enough credibility for us to raise money again. It is not a sentence we could have written about ourselves.' },
  { id: 'E063', era: 'e5', year: '2022\u201324', sort: 2022.2, lane: 'dehat', who: 'DEHAT', place: 'Bahraich', prog: 'School of Leadership',
    title: 'A Second Line of Leadership',
    story: 'Money that was not tied to a project paid for training, for insurance, and for programme leaders with the authority to decide without asking one person first. The point of the spending was to make the organisation harder to kill.' },
  { id: 'E069', era: 'e5', year: '2023\u201326', sort: 2023, lane: 'dehat', who: 'DEHAT', place: 'The four districts', prog: 'All',
    title: 'Four Programmes instead of a pile of Projects',
    story: 'Human Protection, Climate Justice, Rights and Entitlements and the School of Leadership became the structure that sits above the projects, so that a line of work outlives the grant that happened to pay for it.' },
  { id: 'E071', era: 'e5', year: '2024', sort: 2024, lane: 'person', who: 'Devyani Chaturvedi', place: 'International', prog: 'Human Protection', award: true,
    title: 'ICFP Youth Trailblazer',
    story: 'One of forty chosen from more than 550 applicants worldwide, for work on reproductive health with adolescents in the Terai.' },
  { id: 'E075', era: 'e5', year: '2025\u201326', sort: 2025, lane: 'community', who: 'Women farmers', place: 'Bahraich', prog: 'Climate Justice',
    title: 'SWARAJ puts women farmers in charge',
    story: 'Agroecology, kitchen gardens, group savings and a seat at village planning, led by the women who actually farm the land rather than by the men listed as owning it.' },
  { id: 'E077', era: 'e5', year: '2026', sort: 2026, lane: 'person', who: 'Devyani Chaturvedi', place: 'National', prog: 'All',
    title: 'Leading through Dilemmas',
    story: 'She wrote about the loss, the care work and the transition, so that the next organisation to lose its founder has something to read at four in the morning.',
    links: [{ label: 'Leading through Dilemmas \u2014 Dasra (PDF)', href: 'https://dasra.org/pdf/resources/1779171424.pdf' }] },
  { id: 'E079', era: 'e5', year: '2026', sort: 2026.1, lane: 'dehat', who: 'DEHAT', place: 'Bahraich', prog: 'All',
    title: 'Renewing the Board, lawfully',
    story: 'Minutes now distinguish who may observe from who may vote, while the registration procedures catch up. It is slower than appointing friends, and that is exactly the point.' },
];
